-- ----------------------------
-- Sequence structure for gen_table_column_column_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "ruoyi"."gen_table_column_column_id_seq";
CREATE SEQUENCE "ruoyi"."gen_table_column_column_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for gen_table_table_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "ruoyi"."gen_table_table_id_seq";
CREATE SEQUENCE "ruoyi"."gen_table_table_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for sys_config_config_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "ruoyi"."sys_config_config_id_seq";
CREATE SEQUENCE "ruoyi"."sys_config_config_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for sys_dept_dept_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "ruoyi"."sys_dept_dept_id_seq";
CREATE SEQUENCE "ruoyi"."sys_dept_dept_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for sys_dict_data_dict_code_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "ruoyi"."sys_dict_data_dict_code_seq";
CREATE SEQUENCE "ruoyi"."sys_dict_data_dict_code_seq" 
INCREMENT 1
MINVALUE  100
MAXVALUE 9223372036854775807
START 100
CACHE 100;

-- ----------------------------
-- Sequence structure for sys_dict_type_dict_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "ruoyi"."sys_dict_type_dict_id_seq";
CREATE SEQUENCE "ruoyi"."sys_dict_type_dict_id_seq" 
INCREMENT 1
MINVALUE  1111
MAXVALUE 9223372036854775807
START 1111
CACHE 1111;

-- ----------------------------
-- Sequence structure for sys_job_job_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "ruoyi"."sys_job_job_id_seq";
CREATE SEQUENCE "ruoyi"."sys_job_job_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for sys_job_log_job_log_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "ruoyi"."sys_job_log_job_log_id_seq";
CREATE SEQUENCE "ruoyi"."sys_job_log_job_log_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for sys_logininfor_info_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "ruoyi"."sys_logininfor_info_id_seq";
CREATE SEQUENCE "ruoyi"."sys_logininfor_info_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for sys_menu_menu_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "ruoyi"."sys_menu_menu_id_seq";
CREATE SEQUENCE "ruoyi"."sys_menu_menu_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for sys_notice_notice_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "ruoyi"."sys_notice_notice_id_seq";
CREATE SEQUENCE "ruoyi"."sys_notice_notice_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for sys_oper_log_oper_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "ruoyi"."sys_oper_log_oper_id_seq";
CREATE SEQUENCE "ruoyi"."sys_oper_log_oper_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for sys_post_post_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "ruoyi"."sys_post_post_id_seq";
CREATE SEQUENCE "ruoyi"."sys_post_post_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for sys_role_role_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "ruoyi"."sys_role_role_id_seq";
CREATE SEQUENCE "ruoyi"."sys_role_role_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for sys_user_user_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "ruoyi"."sys_user_user_id_seq";
CREATE SEQUENCE "ruoyi"."sys_user_user_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Table structure for gen_table
-- ----------------------------
DROP TABLE IF EXISTS "ruoyi"."gen_table";
CREATE TABLE "ruoyi"."gen_table" (
  "table_id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "table_name" varchar(200) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "table_comment" varchar(500) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "sub_table_name" varchar(64) COLLATE "pg_catalog"."default",
  "sub_table_fk_name" varchar(64) COLLATE "pg_catalog"."default",
  "class_name" varchar(100) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "tpl_category" varchar(200) COLLATE "pg_catalog"."default" DEFAULT 'crud'::character varying,
  "tpl_web_type" varchar(30) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "package_name" varchar(100) COLLATE "pg_catalog"."default",
  "module_name" varchar(255) COLLATE "pg_catalog"."default",
  "business_name" varchar(255) COLLATE "pg_catalog"."default",
  "function_name" varchar(255) COLLATE "pg_catalog"."default",
  "function_author" varchar(50) COLLATE "pg_catalog"."default",
  "gen_type" char(1) COLLATE "pg_catalog"."default" DEFAULT '0'::bpchar,
  "gen_path" varchar(200) COLLATE "pg_catalog"."default" DEFAULT '/'::character varying,
  "options" varchar(1000) COLLATE "pg_catalog"."default",
  "create_by" varchar(64) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "create_time" timestamp(6),
  "update_by" varchar(64) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "update_time" timestamp(6),
  "remark" varchar(500) COLLATE "pg_catalog"."default"
)
;
COMMENT ON COLUMN "ruoyi"."gen_table"."table_id" IS '编号';
COMMENT ON COLUMN "ruoyi"."gen_table"."table_name" IS '表名称';
COMMENT ON COLUMN "ruoyi"."gen_table"."table_comment" IS '表描述';
COMMENT ON COLUMN "ruoyi"."gen_table"."sub_table_name" IS '关联子表的表名';
COMMENT ON COLUMN "ruoyi"."gen_table"."sub_table_fk_name" IS '子表关联的外键名';
COMMENT ON COLUMN "ruoyi"."gen_table"."class_name" IS '实体类名称';
COMMENT ON COLUMN "ruoyi"."gen_table"."tpl_category" IS '使用的模板（crud单表操作 tree树表操作）';
COMMENT ON COLUMN "ruoyi"."gen_table"."tpl_web_type" IS '前端模板类型（element-ui模版 element-plus模版）';
COMMENT ON COLUMN "ruoyi"."gen_table"."package_name" IS '生成包路径';
COMMENT ON COLUMN "ruoyi"."gen_table"."module_name" IS '生成模块名';
COMMENT ON COLUMN "ruoyi"."gen_table"."business_name" IS '生成业务名';
COMMENT ON COLUMN "ruoyi"."gen_table"."function_name" IS '生成功能名';
COMMENT ON COLUMN "ruoyi"."gen_table"."function_author" IS '生成功能作者';
COMMENT ON COLUMN "ruoyi"."gen_table"."gen_type" IS '生成代码方式（0zip压缩包 1自定义路径）';
COMMENT ON COLUMN "ruoyi"."gen_table"."gen_path" IS '生成路径（不填默认项目路径）';
COMMENT ON COLUMN "ruoyi"."gen_table"."options" IS '其它生成选项';
COMMENT ON COLUMN "ruoyi"."gen_table"."create_by" IS '创建者';
COMMENT ON COLUMN "ruoyi"."gen_table"."create_time" IS '创建时间';
COMMENT ON COLUMN "ruoyi"."gen_table"."update_by" IS '更新者';
COMMENT ON COLUMN "ruoyi"."gen_table"."update_time" IS '更新时间';
COMMENT ON COLUMN "ruoyi"."gen_table"."remark" IS '备注';

-- ----------------------------
-- Records of gen_table
-- ----------------------------

-- ----------------------------
-- Table structure for gen_table_column
-- ----------------------------
DROP TABLE IF EXISTS "ruoyi"."gen_table_column";
CREATE TABLE "ruoyi"."gen_table_column" (
  "column_id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "table_id" int8,
  "column_name" varchar(200) COLLATE "pg_catalog"."default",
  "column_comment" varchar(500) COLLATE "pg_catalog"."default",
  "column_type" varchar(100) COLLATE "pg_catalog"."default",
  "java_type" varchar(500) COLLATE "pg_catalog"."default",
  "java_field" varchar(200) COLLATE "pg_catalog"."default",
  "is_pk" char(1) COLLATE "pg_catalog"."default",
  "is_increment" char(1) COLLATE "pg_catalog"."default",
  "is_required" char(1) COLLATE "pg_catalog"."default",
  "is_insert" char(1) COLLATE "pg_catalog"."default",
  "is_edit" char(1) COLLATE "pg_catalog"."default",
  "is_list" char(1) COLLATE "pg_catalog"."default",
  "is_query" char(1) COLLATE "pg_catalog"."default",
  "query_type" varchar(200) COLLATE "pg_catalog"."default" DEFAULT 'EQ'::character varying,
  "html_type" varchar(200) COLLATE "pg_catalog"."default",
  "dict_type" varchar(200) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "sort" int4,
  "create_by" varchar(64) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "create_time" timestamp(6),
  "update_by" varchar(64) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "update_time" timestamp(6)
)
;
COMMENT ON COLUMN "ruoyi"."gen_table_column"."column_id" IS '编号';
COMMENT ON COLUMN "ruoyi"."gen_table_column"."table_id" IS '归属表编号';
COMMENT ON COLUMN "ruoyi"."gen_table_column"."column_name" IS '列名称';
COMMENT ON COLUMN "ruoyi"."gen_table_column"."column_comment" IS '列描述';
COMMENT ON COLUMN "ruoyi"."gen_table_column"."column_type" IS '列类型';
COMMENT ON COLUMN "ruoyi"."gen_table_column"."java_type" IS 'JAVA类型';
COMMENT ON COLUMN "ruoyi"."gen_table_column"."java_field" IS 'JAVA字段名';
COMMENT ON COLUMN "ruoyi"."gen_table_column"."is_pk" IS '是否主键（1是）';
COMMENT ON COLUMN "ruoyi"."gen_table_column"."is_increment" IS '是否自增（1是）';
COMMENT ON COLUMN "ruoyi"."gen_table_column"."is_required" IS '是否必填（1是）';
COMMENT ON COLUMN "ruoyi"."gen_table_column"."is_insert" IS '是否为插入字段（1是）';
COMMENT ON COLUMN "ruoyi"."gen_table_column"."is_edit" IS '是否编辑字段（1是）';
COMMENT ON COLUMN "ruoyi"."gen_table_column"."is_list" IS '是否列表字段（1是）';
COMMENT ON COLUMN "ruoyi"."gen_table_column"."is_query" IS '是否查询字段（1是）';
COMMENT ON COLUMN "ruoyi"."gen_table_column"."query_type" IS '查询方式（等于、不等于、大于、小于、范围）';
COMMENT ON COLUMN "ruoyi"."gen_table_column"."html_type" IS '显示类型（文本框、文本域、下拉框、复选框、单选框、日期控件）';
COMMENT ON COLUMN "ruoyi"."gen_table_column"."dict_type" IS '字典类型';
COMMENT ON COLUMN "ruoyi"."gen_table_column"."sort" IS '排序';
COMMENT ON COLUMN "ruoyi"."gen_table_column"."create_by" IS '创建者';
COMMENT ON COLUMN "ruoyi"."gen_table_column"."create_time" IS '创建时间';
COMMENT ON COLUMN "ruoyi"."gen_table_column"."update_by" IS '更新者';
COMMENT ON COLUMN "ruoyi"."gen_table_column"."update_time" IS '更新时间';

-- ----------------------------
-- Records of gen_table_column
-- ----------------------------

-- ----------------------------
-- Table structure for qrtz_blob_triggers
-- ----------------------------
DROP TABLE IF EXISTS "ruoyi"."qrtz_blob_triggers";
CREATE TABLE "ruoyi"."qrtz_blob_triggers" (
  "sched_name" varchar(120) COLLATE "pg_catalog"."default" NOT NULL,
  "trigger_name" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
  "trigger_group" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
  "blob_data" bytea
)
;
COMMENT ON COLUMN "ruoyi"."qrtz_blob_triggers"."sched_name" IS '调度名称';
COMMENT ON COLUMN "ruoyi"."qrtz_blob_triggers"."trigger_name" IS 'qrtz_triggers表trigger_name的外键';
COMMENT ON COLUMN "ruoyi"."qrtz_blob_triggers"."trigger_group" IS 'qrtz_triggers表trigger_group的外键';
COMMENT ON COLUMN "ruoyi"."qrtz_blob_triggers"."blob_data" IS '存放持久化Trigger对象';

-- ----------------------------
-- Records of qrtz_blob_triggers
-- ----------------------------

-- ----------------------------
-- Table structure for qrtz_calendars
-- ----------------------------
DROP TABLE IF EXISTS "ruoyi"."qrtz_calendars";
CREATE TABLE "ruoyi"."qrtz_calendars" (
  "sched_name" varchar(120) COLLATE "pg_catalog"."default" NOT NULL,
  "calendar_name" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
  "calendar" bytea NOT NULL
)
;
COMMENT ON COLUMN "ruoyi"."qrtz_calendars"."sched_name" IS '调度名称';
COMMENT ON COLUMN "ruoyi"."qrtz_calendars"."calendar_name" IS '日历名称';
COMMENT ON COLUMN "ruoyi"."qrtz_calendars"."calendar" IS '存放持久化calendar对象';

-- ----------------------------
-- Records of qrtz_calendars
-- ----------------------------

-- ----------------------------
-- Table structure for qrtz_cron_triggers
-- ----------------------------
DROP TABLE IF EXISTS "ruoyi"."qrtz_cron_triggers";
CREATE TABLE "ruoyi"."qrtz_cron_triggers" (
  "sched_name" varchar(120) COLLATE "pg_catalog"."default" NOT NULL,
  "trigger_name" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
  "trigger_group" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
  "cron_expression" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
  "time_zone_id" varchar(80) COLLATE "pg_catalog"."default"
)
;
COMMENT ON COLUMN "ruoyi"."qrtz_cron_triggers"."sched_name" IS '调度名称';
COMMENT ON COLUMN "ruoyi"."qrtz_cron_triggers"."trigger_name" IS 'qrtz_triggers表trigger_name的外键';
COMMENT ON COLUMN "ruoyi"."qrtz_cron_triggers"."trigger_group" IS 'qrtz_triggers表trigger_group的外键';
COMMENT ON COLUMN "ruoyi"."qrtz_cron_triggers"."cron_expression" IS 'cron表达式';
COMMENT ON COLUMN "ruoyi"."qrtz_cron_triggers"."time_zone_id" IS '时区';

-- ----------------------------
-- Records of qrtz_cron_triggers
-- ----------------------------

-- ----------------------------
-- Table structure for qrtz_fired_triggers
-- ----------------------------
DROP TABLE IF EXISTS "ruoyi"."qrtz_fired_triggers";
CREATE TABLE "ruoyi"."qrtz_fired_triggers" (
  "sched_name" varchar(120) COLLATE "pg_catalog"."default" NOT NULL,
  "entry_id" varchar(95) COLLATE "pg_catalog"."default" NOT NULL,
  "trigger_name" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
  "trigger_group" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
  "instance_name" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
  "fired_time" int8 NOT NULL,
  "sched_time" int8 NOT NULL,
  "priority" int4 NOT NULL,
  "state" varchar(16) COLLATE "pg_catalog"."default" NOT NULL,
  "job_name" varchar(200) COLLATE "pg_catalog"."default",
  "job_group" varchar(200) COLLATE "pg_catalog"."default",
  "is_nonconcurrent" varchar(1) COLLATE "pg_catalog"."default",
  "requests_recovery" varchar(1) COLLATE "pg_catalog"."default"
)
;
COMMENT ON COLUMN "ruoyi"."qrtz_fired_triggers"."sched_name" IS '调度名称';
COMMENT ON COLUMN "ruoyi"."qrtz_fired_triggers"."entry_id" IS '调度器实例id';
COMMENT ON COLUMN "ruoyi"."qrtz_fired_triggers"."trigger_name" IS 'qrtz_triggers表trigger_name的外键';
COMMENT ON COLUMN "ruoyi"."qrtz_fired_triggers"."trigger_group" IS 'qrtz_triggers表trigger_group的外键';
COMMENT ON COLUMN "ruoyi"."qrtz_fired_triggers"."instance_name" IS '调度器实例名';
COMMENT ON COLUMN "ruoyi"."qrtz_fired_triggers"."fired_time" IS '触发的时间';
COMMENT ON COLUMN "ruoyi"."qrtz_fired_triggers"."sched_time" IS '定时器制定的时间';
COMMENT ON COLUMN "ruoyi"."qrtz_fired_triggers"."priority" IS '优先级';
COMMENT ON COLUMN "ruoyi"."qrtz_fired_triggers"."state" IS '状态';
COMMENT ON COLUMN "ruoyi"."qrtz_fired_triggers"."job_name" IS '任务名称';
COMMENT ON COLUMN "ruoyi"."qrtz_fired_triggers"."job_group" IS '任务组名';
COMMENT ON COLUMN "ruoyi"."qrtz_fired_triggers"."is_nonconcurrent" IS '是否并发';
COMMENT ON COLUMN "ruoyi"."qrtz_fired_triggers"."requests_recovery" IS '是否接受恢复执行';

-- ----------------------------
-- Records of qrtz_fired_triggers
-- ----------------------------

-- ----------------------------
-- Table structure for qrtz_job_details
-- ----------------------------
DROP TABLE IF EXISTS "ruoyi"."qrtz_job_details";
CREATE TABLE "ruoyi"."qrtz_job_details" (
  "sched_name" varchar(120) COLLATE "pg_catalog"."default" NOT NULL,
  "job_name" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
  "job_group" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
  "description" varchar(250) COLLATE "pg_catalog"."default",
  "job_class_name" varchar(250) COLLATE "pg_catalog"."default" NOT NULL,
  "is_durable" varchar(1) COLLATE "pg_catalog"."default" NOT NULL,
  "is_nonconcurrent" varchar(1) COLLATE "pg_catalog"."default" NOT NULL,
  "is_update_data" varchar(1) COLLATE "pg_catalog"."default" NOT NULL,
  "requests_recovery" varchar(1) COLLATE "pg_catalog"."default" NOT NULL,
  "job_data" bytea
)
;
COMMENT ON COLUMN "ruoyi"."qrtz_job_details"."sched_name" IS '调度名称';
COMMENT ON COLUMN "ruoyi"."qrtz_job_details"."job_name" IS '任务名称';
COMMENT ON COLUMN "ruoyi"."qrtz_job_details"."job_group" IS '任务组名';
COMMENT ON COLUMN "ruoyi"."qrtz_job_details"."description" IS '相关介绍';
COMMENT ON COLUMN "ruoyi"."qrtz_job_details"."job_class_name" IS '执行任务类名称';
COMMENT ON COLUMN "ruoyi"."qrtz_job_details"."is_durable" IS '是否持久化';
COMMENT ON COLUMN "ruoyi"."qrtz_job_details"."is_nonconcurrent" IS '是否并发';
COMMENT ON COLUMN "ruoyi"."qrtz_job_details"."is_update_data" IS '是否更新数据';
COMMENT ON COLUMN "ruoyi"."qrtz_job_details"."requests_recovery" IS '是否接受恢复执行';
COMMENT ON COLUMN "ruoyi"."qrtz_job_details"."job_data" IS '存放持久化job对象';

-- ----------------------------
-- Records of qrtz_job_details
-- ----------------------------

-- ----------------------------
-- Table structure for qrtz_locks
-- ----------------------------
DROP TABLE IF EXISTS "ruoyi"."qrtz_locks";
CREATE TABLE "ruoyi"."qrtz_locks" (
  "sched_name" varchar(120) COLLATE "pg_catalog"."default" NOT NULL,
  "lock_name" varchar(40) COLLATE "pg_catalog"."default" NOT NULL
)
;
COMMENT ON COLUMN "ruoyi"."qrtz_locks"."sched_name" IS '调度名称';
COMMENT ON COLUMN "ruoyi"."qrtz_locks"."lock_name" IS '悲观锁名称';

-- ----------------------------
-- Records of qrtz_locks
-- ----------------------------

-- ----------------------------
-- Table structure for qrtz_paused_trigger_grps
-- ----------------------------
DROP TABLE IF EXISTS "ruoyi"."qrtz_paused_trigger_grps";
CREATE TABLE "ruoyi"."qrtz_paused_trigger_grps" (
  "sched_name" varchar(120) COLLATE "pg_catalog"."default" NOT NULL,
  "trigger_group" varchar(200) COLLATE "pg_catalog"."default" NOT NULL
)
;
COMMENT ON COLUMN "ruoyi"."qrtz_paused_trigger_grps"."sched_name" IS '调度名称';
COMMENT ON COLUMN "ruoyi"."qrtz_paused_trigger_grps"."trigger_group" IS 'qrtz_triggers表trigger_group的外键';

-- ----------------------------
-- Records of qrtz_paused_trigger_grps
-- ----------------------------

-- ----------------------------
-- Table structure for qrtz_scheduler_state
-- ----------------------------
DROP TABLE IF EXISTS "ruoyi"."qrtz_scheduler_state";
CREATE TABLE "ruoyi"."qrtz_scheduler_state" (
  "sched_name" varchar(120) COLLATE "pg_catalog"."default" NOT NULL,
  "instance_name" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
  "last_checkin_time" int8 NOT NULL,
  "checkin_interval" int8 NOT NULL
)
;
COMMENT ON COLUMN "ruoyi"."qrtz_scheduler_state"."sched_name" IS '调度名称';
COMMENT ON COLUMN "ruoyi"."qrtz_scheduler_state"."instance_name" IS '实例名称';
COMMENT ON COLUMN "ruoyi"."qrtz_scheduler_state"."last_checkin_time" IS '上次检查时间';
COMMENT ON COLUMN "ruoyi"."qrtz_scheduler_state"."checkin_interval" IS '检查间隔时间';

-- ----------------------------
-- Records of qrtz_scheduler_state
-- ----------------------------

-- ----------------------------
-- Table structure for qrtz_simple_triggers
-- ----------------------------
DROP TABLE IF EXISTS "ruoyi"."qrtz_simple_triggers";
CREATE TABLE "ruoyi"."qrtz_simple_triggers" (
  "sched_name" varchar(120) COLLATE "pg_catalog"."default" NOT NULL,
  "trigger_name" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
  "trigger_group" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
  "repeat_count" int8 NOT NULL,
  "repeat_interval" int8 NOT NULL,
  "times_triggered" int8 NOT NULL
)
;
COMMENT ON COLUMN "ruoyi"."qrtz_simple_triggers"."sched_name" IS '调度名称';
COMMENT ON COLUMN "ruoyi"."qrtz_simple_triggers"."trigger_name" IS 'qrtz_triggers表trigger_name的外键';
COMMENT ON COLUMN "ruoyi"."qrtz_simple_triggers"."trigger_group" IS 'qrtz_triggers表trigger_group的外键';
COMMENT ON COLUMN "ruoyi"."qrtz_simple_triggers"."repeat_count" IS '重复的次数统计';
COMMENT ON COLUMN "ruoyi"."qrtz_simple_triggers"."repeat_interval" IS '重复的间隔时间';
COMMENT ON COLUMN "ruoyi"."qrtz_simple_triggers"."times_triggered" IS '已经触发的次数';

-- ----------------------------
-- Records of qrtz_simple_triggers
-- ----------------------------

-- ----------------------------
-- Table structure for qrtz_simprop_triggers
-- ----------------------------
DROP TABLE IF EXISTS "ruoyi"."qrtz_simprop_triggers";
CREATE TABLE "ruoyi"."qrtz_simprop_triggers" (
  "sched_name" varchar(120) COLLATE "pg_catalog"."default" NOT NULL,
  "trigger_name" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
  "trigger_group" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
  "str_prop_1" varchar(512) COLLATE "pg_catalog"."default",
  "str_prop_2" varchar(512) COLLATE "pg_catalog"."default",
  "str_prop_3" varchar(512) COLLATE "pg_catalog"."default",
  "int_prop_1" int4,
  "int_prop_2" int4,
  "long_prop_1" int8,
  "long_prop_2" int8,
  "dec_prop_1" numeric(13,4),
  "dec_prop_2" numeric(13,4),
  "bool_prop_1" varchar(1) COLLATE "pg_catalog"."default",
  "bool_prop_2" varchar(1) COLLATE "pg_catalog"."default"
)
;
COMMENT ON COLUMN "ruoyi"."qrtz_simprop_triggers"."sched_name" IS '调度名称';
COMMENT ON COLUMN "ruoyi"."qrtz_simprop_triggers"."trigger_name" IS 'qrtz_triggers表trigger_name的外键';
COMMENT ON COLUMN "ruoyi"."qrtz_simprop_triggers"."trigger_group" IS 'qrtz_triggers表trigger_group的外键';
COMMENT ON COLUMN "ruoyi"."qrtz_simprop_triggers"."str_prop_1" IS 'String类型的trigger的第一个参数';
COMMENT ON COLUMN "ruoyi"."qrtz_simprop_triggers"."str_prop_2" IS 'String类型的trigger的第二个参数';
COMMENT ON COLUMN "ruoyi"."qrtz_simprop_triggers"."str_prop_3" IS 'String类型的trigger的第三个参数';
COMMENT ON COLUMN "ruoyi"."qrtz_simprop_triggers"."int_prop_1" IS 'int类型的trigger的第一个参数';
COMMENT ON COLUMN "ruoyi"."qrtz_simprop_triggers"."int_prop_2" IS 'int类型的trigger的第二个参数';
COMMENT ON COLUMN "ruoyi"."qrtz_simprop_triggers"."long_prop_1" IS 'long类型的trigger的第一个参数';
COMMENT ON COLUMN "ruoyi"."qrtz_simprop_triggers"."long_prop_2" IS 'long类型的trigger的第二个参数';
COMMENT ON COLUMN "ruoyi"."qrtz_simprop_triggers"."dec_prop_1" IS 'decimal类型的trigger的第一个参数';
COMMENT ON COLUMN "ruoyi"."qrtz_simprop_triggers"."dec_prop_2" IS 'decimal类型的trigger的第二个参数';
COMMENT ON COLUMN "ruoyi"."qrtz_simprop_triggers"."bool_prop_1" IS 'Boolean类型的trigger的第一个参数';
COMMENT ON COLUMN "ruoyi"."qrtz_simprop_triggers"."bool_prop_2" IS 'Boolean类型的trigger的第二个参数';

-- ----------------------------
-- Records of qrtz_simprop_triggers
-- ----------------------------

-- ----------------------------
-- Table structure for qrtz_triggers
-- ----------------------------
DROP TABLE IF EXISTS "ruoyi"."qrtz_triggers";
CREATE TABLE "ruoyi"."qrtz_triggers" (
  "sched_name" varchar(120) COLLATE "pg_catalog"."default" NOT NULL,
  "trigger_name" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
  "trigger_group" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
  "job_name" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
  "job_group" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
  "description" varchar(250) COLLATE "pg_catalog"."default",
  "next_fire_time" int8,
  "prev_fire_time" int8,
  "priority" int4,
  "trigger_state" varchar(16) COLLATE "pg_catalog"."default" NOT NULL,
  "trigger_type" varchar(8) COLLATE "pg_catalog"."default" NOT NULL,
  "start_time" int8 NOT NULL,
  "end_time" int8,
  "calendar_name" varchar(200) COLLATE "pg_catalog"."default",
  "misfire_instr" int2,
  "job_data" bytea
)
;
COMMENT ON COLUMN "ruoyi"."qrtz_triggers"."sched_name" IS '调度名称';
COMMENT ON COLUMN "ruoyi"."qrtz_triggers"."trigger_name" IS '触发器的名字';
COMMENT ON COLUMN "ruoyi"."qrtz_triggers"."trigger_group" IS '触发器所属组的名字';
COMMENT ON COLUMN "ruoyi"."qrtz_triggers"."job_name" IS 'qrtz_job_details表job_name的外键';
COMMENT ON COLUMN "ruoyi"."qrtz_triggers"."job_group" IS 'qrtz_job_details表job_group的外键';
COMMENT ON COLUMN "ruoyi"."qrtz_triggers"."description" IS '相关介绍';
COMMENT ON COLUMN "ruoyi"."qrtz_triggers"."next_fire_time" IS '上一次触发时间（毫秒）';
COMMENT ON COLUMN "ruoyi"."qrtz_triggers"."prev_fire_time" IS '下一次触发时间（默认为-1表示不触发）';
COMMENT ON COLUMN "ruoyi"."qrtz_triggers"."priority" IS '优先级';
COMMENT ON COLUMN "ruoyi"."qrtz_triggers"."trigger_state" IS '触发器状态';
COMMENT ON COLUMN "ruoyi"."qrtz_triggers"."trigger_type" IS '触发器的类型';
COMMENT ON COLUMN "ruoyi"."qrtz_triggers"."start_time" IS '开始时间';
COMMENT ON COLUMN "ruoyi"."qrtz_triggers"."end_time" IS '结束时间';
COMMENT ON COLUMN "ruoyi"."qrtz_triggers"."calendar_name" IS '日程表名称';
COMMENT ON COLUMN "ruoyi"."qrtz_triggers"."misfire_instr" IS '补偿执行的策略';
COMMENT ON COLUMN "ruoyi"."qrtz_triggers"."job_data" IS '存放持久化job对象';

-- ----------------------------
-- Records of qrtz_triggers
-- ----------------------------

-- ----------------------------
-- Table structure for sys_config
-- ----------------------------
DROP TABLE IF EXISTS "ruoyi"."sys_config";
CREATE TABLE "ruoyi"."sys_config" (
  "config_id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "config_name" varchar(100) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "config_key" varchar(100) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "config_value" varchar(500) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "config_type" char(1) COLLATE "pg_catalog"."default" DEFAULT 'N'::bpchar,
  "create_by" varchar(64) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "create_time" timestamp(6),
  "update_by" varchar(64) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "update_time" timestamp(6),
  "remark" varchar(500) COLLATE "pg_catalog"."default"
)
;
COMMENT ON COLUMN "ruoyi"."sys_config"."config_id" IS '参数主键';
COMMENT ON COLUMN "ruoyi"."sys_config"."config_name" IS '参数名称';
COMMENT ON COLUMN "ruoyi"."sys_config"."config_key" IS '参数键名';
COMMENT ON COLUMN "ruoyi"."sys_config"."config_value" IS '参数键值';
COMMENT ON COLUMN "ruoyi"."sys_config"."config_type" IS '系统内置（Y是 N否）';
COMMENT ON COLUMN "ruoyi"."sys_config"."create_by" IS '创建者';
COMMENT ON COLUMN "ruoyi"."sys_config"."create_time" IS '创建时间';
COMMENT ON COLUMN "ruoyi"."sys_config"."update_by" IS '更新者';
COMMENT ON COLUMN "ruoyi"."sys_config"."update_time" IS '更新时间';
COMMENT ON COLUMN "ruoyi"."sys_config"."remark" IS '备注';

-- ----------------------------
-- Records of sys_config
-- ----------------------------
INSERT INTO "ruoyi"."sys_config" VALUES (1, '主框架页-默认皮肤样式名称', 'sys.index.skinName', 'skin-blue', 'Y', 'admin', '2024-07-18 08:50:07', '', NULL, '蓝色 skin-blue、绿色 skin-green、紫色 skin-purple、红色 skin-red、黄色 skin-yellow');
INSERT INTO "ruoyi"."sys_config" VALUES (2, '用户管理-账号初始密码', 'sys.user.initPassword', 'Abc_12389', 'Y', 'admin', '2024-07-18 08:50:07', '', NULL, '初始化密码 Abc_12389');
INSERT INTO "ruoyi"."sys_config" VALUES (3, '主框架页-侧边栏主题', 'sys.index.sideTheme', 'theme-dark', 'Y', 'admin', '2024-07-18 08:50:07', '', NULL, '深色主题theme-dark，浅色主题theme-light');
INSERT INTO "ruoyi"."sys_config" VALUES (4, '账号自助-验证码开关', 'sys.account.captchaEnabled', 'true', 'Y', 'admin', '2024-07-18 08:50:07', '', NULL, '是否开启验证码功能（true开启，false关闭）');
INSERT INTO "ruoyi"."sys_config" VALUES (5, '账号自助-是否开启用户注册功能', 'sys.account.registerUser', 'false', 'Y', 'admin', '2024-07-18 08:50:07', '', NULL, '是否开启注册用户功能（true开启，false关闭）');
INSERT INTO "ruoyi"."sys_config" VALUES (6, '用户登录-黑名单列表', 'sys.login.blackIPList', '', 'Y', 'admin', '2024-07-18 08:50:07', '', NULL, '设置登录IP黑名单限制，多个匹配项以;分隔，支持匹配（*通配、网段）');
insert into "ruoyi"."sys_config" VALUES (7, '用户管理-初始密码修改策略','sys.account.initPasswordModify','0','Y', 'admin', '2024-07-18 08:50:07','', NULL,'0：初始密码修改策略关闭，没有任何提示，1：提醒用户，如果未修改初始密码，则在登录时就会提醒修改密码对话框');
insert into "ruoyi"."sys_config" values (8, '用户管理-账号密码更新周期','sys.account.passwordValidateDays','0','Y', 'admin', '2024-07-18 08:50:07','', null, '密码更新周期（填写数字，数据初始化值为0不限制，若修改必须为大于0小于365的正整数），如果超过这个周期登录系统时，则在登录时就会提醒修改密码对话框');
insert into "ruoyi"."sys_config" values (9, '用户管理-账号密码尝试登录次数',     'sys.account.tryLoginCount', '0',             'Y', 'admin', '2024-07-18 08:50:07', '', null, '尝试登录次数（格式0-0（尝试次数-锁号时长（分钟）），数据初始化值为0不限制）');

-- ----------------------------
-- Table structure for sys_dept
-- ----------------------------
DROP TABLE IF EXISTS "ruoyi"."sys_dept";
CREATE TABLE "ruoyi"."sys_dept" (
  "dept_id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "parent_id" int8 DEFAULT '0'::bigint,
  "ancestors" varchar(50) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "dept_name" varchar(30) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "order_num" int4 DEFAULT 0,
  "leader" varchar(20) COLLATE "pg_catalog"."default",
  "phone" varchar(11) COLLATE "pg_catalog"."default",
  "email" varchar(50) COLLATE "pg_catalog"."default",
  "status" char(1) COLLATE "pg_catalog"."default" DEFAULT '0'::bpchar,
  "del_flag" char(1) COLLATE "pg_catalog"."default" DEFAULT '0'::bpchar,
  "create_by" varchar(64) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "create_time" timestamp(6),
  "update_by" varchar(64) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "update_time" timestamp(6)
)
;
COMMENT ON COLUMN "ruoyi"."sys_dept"."dept_id" IS '部门id';
COMMENT ON COLUMN "ruoyi"."sys_dept"."parent_id" IS '父部门id';
COMMENT ON COLUMN "ruoyi"."sys_dept"."ancestors" IS '祖级列表';
COMMENT ON COLUMN "ruoyi"."sys_dept"."dept_name" IS '部门名称';
COMMENT ON COLUMN "ruoyi"."sys_dept"."order_num" IS '显示顺序';
COMMENT ON COLUMN "ruoyi"."sys_dept"."leader" IS '负责人';
COMMENT ON COLUMN "ruoyi"."sys_dept"."phone" IS '联系电话';
COMMENT ON COLUMN "ruoyi"."sys_dept"."email" IS '邮箱';
COMMENT ON COLUMN "ruoyi"."sys_dept"."status" IS '部门状态（0正常 1停用）';
COMMENT ON COLUMN "ruoyi"."sys_dept"."del_flag" IS '删除标志（0代表存在 2代表删除）';
COMMENT ON COLUMN "ruoyi"."sys_dept"."create_by" IS '创建者';
COMMENT ON COLUMN "ruoyi"."sys_dept"."create_time" IS '创建时间';
COMMENT ON COLUMN "ruoyi"."sys_dept"."update_by" IS '更新者';
COMMENT ON COLUMN "ruoyi"."sys_dept"."update_time" IS '更新时间';

-- ----------------------------
-- Records of sys_dept
-- ----------------------------
INSERT INTO "ruoyi"."sys_dept" VALUES (100, 0, '0', '总公司', 0, 'admin', '15553502062', 'jiangyanxi@live.com', '0', '0', 'admin', '2024-07-18 08:50:06', 'admin', '2024-07-18 08:58:54');

-- ----------------------------
-- Table structure for sys_dict_data
-- ----------------------------
DROP TABLE IF EXISTS "ruoyi"."sys_dict_data";
CREATE TABLE "ruoyi"."sys_dict_data" (
  "dict_code" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  100
MAXVALUE 9223372036854775807
START 100
CACHE 100
),
  "dict_sort" int4 DEFAULT 0,
  "dict_label" varchar(100) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "dict_value" varchar(100) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "dict_type" varchar(100) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "css_class" varchar(100) COLLATE "pg_catalog"."default",
  "list_class" varchar(100) COLLATE "pg_catalog"."default",
  "is_default" char(1) COLLATE "pg_catalog"."default" DEFAULT 'N'::bpchar,
  "status" char(1) COLLATE "pg_catalog"."default" DEFAULT '0'::bpchar,
  "create_by" varchar(64) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "create_time" timestamp(6),
  "update_by" varchar(64) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "update_time" timestamp(6),
  "remark" varchar(500) COLLATE "pg_catalog"."default"
)
;
COMMENT ON COLUMN "ruoyi"."sys_dict_data"."dict_code" IS '字典编码';
COMMENT ON COLUMN "ruoyi"."sys_dict_data"."dict_sort" IS '字典排序';
COMMENT ON COLUMN "ruoyi"."sys_dict_data"."dict_label" IS '字典标签';
COMMENT ON COLUMN "ruoyi"."sys_dict_data"."dict_value" IS '字典键值';
COMMENT ON COLUMN "ruoyi"."sys_dict_data"."dict_type" IS '字典类型';
COMMENT ON COLUMN "ruoyi"."sys_dict_data"."css_class" IS '样式属性（其他样式扩展）';
COMMENT ON COLUMN "ruoyi"."sys_dict_data"."list_class" IS '表格回显样式';
COMMENT ON COLUMN "ruoyi"."sys_dict_data"."is_default" IS '是否默认（Y是 N否）';
COMMENT ON COLUMN "ruoyi"."sys_dict_data"."status" IS '状态（0正常 1停用）';
COMMENT ON COLUMN "ruoyi"."sys_dict_data"."create_by" IS '创建者';
COMMENT ON COLUMN "ruoyi"."sys_dict_data"."create_time" IS '创建时间';
COMMENT ON COLUMN "ruoyi"."sys_dict_data"."update_by" IS '更新者';
COMMENT ON COLUMN "ruoyi"."sys_dict_data"."update_time" IS '更新时间';
COMMENT ON COLUMN "ruoyi"."sys_dict_data"."remark" IS '备注';

-- ----------------------------
-- Records of sys_dict_data
-- ----------------------------
INSERT INTO "ruoyi"."sys_dict_data" VALUES (1, 1, '男', '0', 'sys_user_sex', '', '', 'Y', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '性别男');
INSERT INTO "ruoyi"."sys_dict_data" VALUES (2, 2, '女', '1', 'sys_user_sex', '', '', 'N', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '性别女');
INSERT INTO "ruoyi"."sys_dict_data" VALUES (3, 3, '未知', '2', 'sys_user_sex', '', '', 'N', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '性别未知');
INSERT INTO "ruoyi"."sys_dict_data" VALUES (4, 1, '显示', '0', 'sys_show_hide', '', 'primary', 'Y', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '显示菜单');
INSERT INTO "ruoyi"."sys_dict_data" VALUES (5, 2, '隐藏', '1', 'sys_show_hide', '', 'danger', 'N', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '隐藏菜单');
INSERT INTO "ruoyi"."sys_dict_data" VALUES (6, 1, '正常', '0', 'sys_normal_disable', '', 'primary', 'Y', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '正常状态');
INSERT INTO "ruoyi"."sys_dict_data" VALUES (7, 2, '停用', '1', 'sys_normal_disable', '', 'danger', 'N', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '停用状态');
INSERT INTO "ruoyi"."sys_dict_data" VALUES (8, 1, '正常', '0', 'sys_job_status', '', 'primary', 'Y', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '正常状态');
INSERT INTO "ruoyi"."sys_dict_data" VALUES (9, 2, '暂停', '1', 'sys_job_status', '', 'danger', 'N', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '停用状态');
INSERT INTO "ruoyi"."sys_dict_data" VALUES (10, 1, '默认', 'DEFAULT', 'sys_job_group', '', '', 'Y', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '默认分组');
INSERT INTO "ruoyi"."sys_dict_data" VALUES (11, 2, '系统', 'SYSTEM', 'sys_job_group', '', '', 'N', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '系统分组');
INSERT INTO "ruoyi"."sys_dict_data" VALUES (12, 1, '是', 'Y', 'sys_yes_no', '', 'primary', 'Y', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '系统默认是');
INSERT INTO "ruoyi"."sys_dict_data" VALUES (13, 2, '否', 'N', 'sys_yes_no', '', 'danger', 'N', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '系统默认否');
INSERT INTO "ruoyi"."sys_dict_data" VALUES (14, 1, '通知', '1', 'sys_notice_type', '', 'warning', 'Y', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '通知');
INSERT INTO "ruoyi"."sys_dict_data" VALUES (15, 2, '公告', '2', 'sys_notice_type', '', 'success', 'N', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '公告');
INSERT INTO "ruoyi"."sys_dict_data" VALUES (16, 1, '正常', '0', 'sys_notice_status', '', 'primary', 'Y', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '正常状态');
INSERT INTO "ruoyi"."sys_dict_data" VALUES (17, 2, '关闭', '1', 'sys_notice_status', '', 'danger', 'N', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '关闭状态');
INSERT INTO "ruoyi"."sys_dict_data" VALUES (18, 99, '其他', '0', 'sys_oper_type', '', 'info', 'N', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '其他操作');
INSERT INTO "ruoyi"."sys_dict_data" VALUES (19, 1, '新增', '1', 'sys_oper_type', '', 'info', 'N', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '新增操作');
INSERT INTO "ruoyi"."sys_dict_data" VALUES (20, 2, '修改', '2', 'sys_oper_type', '', 'info', 'N', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '修改操作');
INSERT INTO "ruoyi"."sys_dict_data" VALUES (21, 3, '删除', '3', 'sys_oper_type', '', 'danger', 'N', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '删除操作');
INSERT INTO "ruoyi"."sys_dict_data" VALUES (22, 4, '授权', '4', 'sys_oper_type', '', 'primary', 'N', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '授权操作');
INSERT INTO "ruoyi"."sys_dict_data" VALUES (23, 5, '导出', '5', 'sys_oper_type', '', 'warning', 'N', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '导出操作');
INSERT INTO "ruoyi"."sys_dict_data" VALUES (24, 6, '导入', '6', 'sys_oper_type', '', 'warning', 'N', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '导入操作');
INSERT INTO "ruoyi"."sys_dict_data" VALUES (25, 7, '强退', '7', 'sys_oper_type', '', 'danger', 'N', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '强退操作');
INSERT INTO "ruoyi"."sys_dict_data" VALUES (26, 8, '生成代码', '8', 'sys_oper_type', '', 'warning', 'N', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '生成操作');
INSERT INTO "ruoyi"."sys_dict_data" VALUES (27, 9, '清空数据', '9', 'sys_oper_type', '', 'danger', 'N', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '清空操作');
INSERT INTO "ruoyi"."sys_dict_data" VALUES (28, 1, '成功', '0', 'sys_common_status', '', 'primary', 'N', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '正常状态');
INSERT INTO "ruoyi"."sys_dict_data" VALUES (29, 2, '失败', '1', 'sys_common_status', '', 'danger', 'N', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '停用状态');

-- ----------------------------
-- Table structure for sys_dict_type
-- ----------------------------
DROP TABLE IF EXISTS "ruoyi"."sys_dict_type";
CREATE TABLE "ruoyi"."sys_dict_type" (
  "dict_id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1111
MAXVALUE 9223372036854775807
START 1111
CACHE 1111
),
  "dict_name" varchar(100) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "dict_type" varchar(100) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "status" char(1) COLLATE "pg_catalog"."default" DEFAULT '0'::bpchar,
  "create_by" varchar(64) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "create_time" timestamp(6),
  "update_by" varchar(64) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "update_time" timestamp(6),
  "remark" varchar(500) COLLATE "pg_catalog"."default"
)
;
COMMENT ON COLUMN "ruoyi"."sys_dict_type"."dict_id" IS '字典主键';
COMMENT ON COLUMN "ruoyi"."sys_dict_type"."dict_name" IS '字典名称';
COMMENT ON COLUMN "ruoyi"."sys_dict_type"."dict_type" IS '字典类型';
COMMENT ON COLUMN "ruoyi"."sys_dict_type"."status" IS '状态（0正常 1停用）';
COMMENT ON COLUMN "ruoyi"."sys_dict_type"."create_by" IS '创建者';
COMMENT ON COLUMN "ruoyi"."sys_dict_type"."create_time" IS '创建时间';
COMMENT ON COLUMN "ruoyi"."sys_dict_type"."update_by" IS '更新者';
COMMENT ON COLUMN "ruoyi"."sys_dict_type"."update_time" IS '更新时间';
COMMENT ON COLUMN "ruoyi"."sys_dict_type"."remark" IS '备注';

-- ----------------------------
-- Records of sys_dict_type
-- ----------------------------
INSERT INTO "ruoyi"."sys_dict_type" VALUES (1, '用户性别', 'sys_user_sex', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '用户性别列表');
INSERT INTO "ruoyi"."sys_dict_type" VALUES (2, '菜单状态', 'sys_show_hide', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '菜单状态列表');
INSERT INTO "ruoyi"."sys_dict_type" VALUES (3, '系统开关', 'sys_normal_disable', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '系统开关列表');
INSERT INTO "ruoyi"."sys_dict_type" VALUES (4, '任务状态', 'sys_job_status', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '任务状态列表');
INSERT INTO "ruoyi"."sys_dict_type" VALUES (5, '任务分组', 'sys_job_group', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '任务分组列表');
INSERT INTO "ruoyi"."sys_dict_type" VALUES (6, '系统是否', 'sys_yes_no', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '系统是否列表');
INSERT INTO "ruoyi"."sys_dict_type" VALUES (7, '通知类型', 'sys_notice_type', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '通知类型列表');
INSERT INTO "ruoyi"."sys_dict_type" VALUES (8, '通知状态', 'sys_notice_status', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '通知状态列表');
INSERT INTO "ruoyi"."sys_dict_type" VALUES (9, '操作类型', 'sys_oper_type', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '操作类型列表');
INSERT INTO "ruoyi"."sys_dict_type" VALUES (10, '系统状态', 'sys_common_status', '0', 'admin', '2024-07-18 08:50:07', '', NULL, '登录状态列表');

-- ----------------------------
-- Table structure for sys_job
-- ----------------------------
DROP TABLE IF EXISTS "ruoyi"."sys_job";
CREATE TABLE "ruoyi"."sys_job" (
  "job_id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "job_name" varchar(64) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "job_group" varchar(64) COLLATE "pg_catalog"."default" NOT NULL DEFAULT 'DEFAULT'::character varying,
  "invoke_target" varchar(500) COLLATE "pg_catalog"."default" NOT NULL,
  "cron_expression" varchar(255) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "misfire_policy" varchar(20) COLLATE "pg_catalog"."default" DEFAULT '3'::character varying,
  "concurrent" char(1) COLLATE "pg_catalog"."default" DEFAULT '1'::bpchar,
  "status" char(1) COLLATE "pg_catalog"."default" DEFAULT '0'::bpchar,
  "create_by" varchar(64) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "create_time" timestamp(6),
  "update_by" varchar(64) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "update_time" timestamp(6),
  "remark" varchar(500) COLLATE "pg_catalog"."default" DEFAULT ''::character varying
)
;
COMMENT ON COLUMN "ruoyi"."sys_job"."job_id" IS '任务ID';
COMMENT ON COLUMN "ruoyi"."sys_job"."job_name" IS '任务名称';
COMMENT ON COLUMN "ruoyi"."sys_job"."job_group" IS '任务组名';
COMMENT ON COLUMN "ruoyi"."sys_job"."invoke_target" IS '调用目标字符串';
COMMENT ON COLUMN "ruoyi"."sys_job"."cron_expression" IS 'cron执行表达式';
COMMENT ON COLUMN "ruoyi"."sys_job"."misfire_policy" IS '计划执行错误策略（1立即执行 2执行一次 3放弃执行）';
COMMENT ON COLUMN "ruoyi"."sys_job"."concurrent" IS '是否并发执行（0允许 1禁止）';
COMMENT ON COLUMN "ruoyi"."sys_job"."status" IS '状态（0正常 1暂停）';
COMMENT ON COLUMN "ruoyi"."sys_job"."create_by" IS '创建者';
COMMENT ON COLUMN "ruoyi"."sys_job"."create_time" IS '创建时间';
COMMENT ON COLUMN "ruoyi"."sys_job"."update_by" IS '更新者';
COMMENT ON COLUMN "ruoyi"."sys_job"."update_time" IS '更新时间';
COMMENT ON COLUMN "ruoyi"."sys_job"."remark" IS '备注信息';

-- ----------------------------
-- Records of sys_job
-- ----------------------------
INSERT INTO "ruoyi"."sys_job" VALUES (1, '系统默认（无参）', 'DEFAULT', 'ryTask.ryNoParams', '0/10 * * * * ?', '3', '1', '1', 'admin', '2024-07-18 08:50:07', '', NULL, '');
INSERT INTO "ruoyi"."sys_job" VALUES (2, '系统默认（有参）', 'DEFAULT', 'ryTask.ryParams(''ry'')', '0/15 * * * * ?', '3', '1', '1', 'admin', '2024-07-18 08:50:07', '', NULL, '');
INSERT INTO "ruoyi"."sys_job" VALUES (3, '系统默认（多参）', 'DEFAULT', 'ryTask.ryMultipleParams(''ry'', true, 2000L, 316.50D, 100)', '0/20 * * * * ?', '3', '1', '1', 'admin', '2024-07-18 08:50:07', 'admin', '2025-03-26 13:23:59.293618', '');

-- ----------------------------
-- Table structure for sys_job_log
-- ----------------------------
DROP TABLE IF EXISTS "ruoyi"."sys_job_log";
CREATE TABLE "ruoyi"."sys_job_log" (
  "job_log_id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "job_name" varchar(64) COLLATE "pg_catalog"."default" NOT NULL,
  "job_group" varchar(64) COLLATE "pg_catalog"."default" NOT NULL,
  "invoke_target" varchar(500) COLLATE "pg_catalog"."default" NOT NULL,
  "job_message" varchar(500) COLLATE "pg_catalog"."default",
  "status" char(1) COLLATE "pg_catalog"."default" DEFAULT '0'::bpchar,
  "exception_info" varchar(5000) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "create_time" timestamp(6)
)
;
COMMENT ON COLUMN "ruoyi"."sys_job_log"."job_log_id" IS '任务日志ID';
COMMENT ON COLUMN "ruoyi"."sys_job_log"."job_name" IS '任务名称';
COMMENT ON COLUMN "ruoyi"."sys_job_log"."job_group" IS '任务组名';
COMMENT ON COLUMN "ruoyi"."sys_job_log"."invoke_target" IS '调用目标字符串';
COMMENT ON COLUMN "ruoyi"."sys_job_log"."job_message" IS '日志信息';
COMMENT ON COLUMN "ruoyi"."sys_job_log"."status" IS '执行状态（0正常 1失败）';
COMMENT ON COLUMN "ruoyi"."sys_job_log"."exception_info" IS '异常信息';
COMMENT ON COLUMN "ruoyi"."sys_job_log"."create_time" IS '创建时间';

-- ----------------------------
-- Records of sys_job_log
-- ----------------------------

-- ----------------------------
-- Table structure for sys_logininfor
-- ----------------------------
DROP TABLE IF EXISTS "ruoyi"."sys_logininfor";
CREATE TABLE "ruoyi"."sys_logininfor" (
  "info_id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "user_name" varchar(50) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "ipaddr" varchar(128) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "login_location" varchar(255) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "browser" varchar(50) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "os" varchar(50) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "status" char(1) COLLATE "pg_catalog"."default" DEFAULT '0'::bpchar,
  "msg" varchar(255) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "login_time" timestamp(6)
)
;
COMMENT ON COLUMN "ruoyi"."sys_logininfor"."info_id" IS '访问ID';
COMMENT ON COLUMN "ruoyi"."sys_logininfor"."user_name" IS '用户账号';
COMMENT ON COLUMN "ruoyi"."sys_logininfor"."ipaddr" IS '登录IP地址';
COMMENT ON COLUMN "ruoyi"."sys_logininfor"."login_location" IS '登录地点';
COMMENT ON COLUMN "ruoyi"."sys_logininfor"."browser" IS '浏览器类型';
COMMENT ON COLUMN "ruoyi"."sys_logininfor"."os" IS '操作系统';
COMMENT ON COLUMN "ruoyi"."sys_logininfor"."status" IS '登录状态（0成功 1失败）';
COMMENT ON COLUMN "ruoyi"."sys_logininfor"."msg" IS '提示消息';
COMMENT ON COLUMN "ruoyi"."sys_logininfor"."login_time" IS '访问时间';

-- ----------------------------
-- Records of sys_logininfor
-- ----------------------------
INSERT INTO "ruoyi"."sys_logininfor" VALUES (1, 'admin', '127.0.0.1', '内网IP', 'Chrome 13', 'Windows 10', '0', '登录成功', '2025-03-26 14:56:06.94323');

-- ----------------------------
-- Table structure for sys_menu
-- ----------------------------
DROP TABLE IF EXISTS "ruoyi"."sys_menu";
CREATE TABLE "ruoyi"."sys_menu" (
  "menu_id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "menu_name" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "parent_id" int8 DEFAULT '0'::bigint,
  "order_num" int4 DEFAULT 0,
  "path" varchar(200) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "component" varchar(255) COLLATE "pg_catalog"."default",
  "query" varchar(255) COLLATE "pg_catalog"."default",
  "route_name" varchar(50) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "is_frame" int4 DEFAULT 1,
  "is_cache" int4 DEFAULT 0,
  "menu_type" char(1) COLLATE "pg_catalog"."default" DEFAULT ''::bpchar,
  "visible" char(1) COLLATE "pg_catalog"."default" DEFAULT '0'::bpchar,
  "status" char(1) COLLATE "pg_catalog"."default" DEFAULT '0'::bpchar,
  "perms" varchar(100) COLLATE "pg_catalog"."default",
  "icon" varchar(100) COLLATE "pg_catalog"."default" DEFAULT '#'::character varying,
  "create_by" varchar(64) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "create_time" timestamp(6),
  "update_by" varchar(64) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "update_time" timestamp(6),
  "remark" varchar(500) COLLATE "pg_catalog"."default" DEFAULT ''::character varying
)
;
COMMENT ON COLUMN "ruoyi"."sys_menu"."menu_id" IS '菜单ID';
COMMENT ON COLUMN "ruoyi"."sys_menu"."menu_name" IS '菜单名称';
COMMENT ON COLUMN "ruoyi"."sys_menu"."parent_id" IS '父菜单ID';
COMMENT ON COLUMN "ruoyi"."sys_menu"."order_num" IS '显示顺序';
COMMENT ON COLUMN "ruoyi"."sys_menu"."path" IS '路由地址';
COMMENT ON COLUMN "ruoyi"."sys_menu"."component" IS '组件路径';
COMMENT ON COLUMN "ruoyi"."sys_menu"."query" IS '路由参数';
COMMENT ON COLUMN "ruoyi"."sys_menu"."route_name" IS '路由名称';
COMMENT ON COLUMN "ruoyi"."sys_menu"."is_frame" IS '是否为外链（0是 1否）';
COMMENT ON COLUMN "ruoyi"."sys_menu"."is_cache" IS '是否缓存（0缓存 1不缓存）';
COMMENT ON COLUMN "ruoyi"."sys_menu"."menu_type" IS '菜单类型（M目录 C菜单 F按钮）';
COMMENT ON COLUMN "ruoyi"."sys_menu"."visible" IS '菜单状态（0显示 1隐藏）';
COMMENT ON COLUMN "ruoyi"."sys_menu"."status" IS '菜单状态（0正常 1停用）';
COMMENT ON COLUMN "ruoyi"."sys_menu"."perms" IS '权限标识';
COMMENT ON COLUMN "ruoyi"."sys_menu"."icon" IS '菜单图标';
COMMENT ON COLUMN "ruoyi"."sys_menu"."create_by" IS '创建者';
COMMENT ON COLUMN "ruoyi"."sys_menu"."create_time" IS '创建时间';
COMMENT ON COLUMN "ruoyi"."sys_menu"."update_by" IS '更新者';
COMMENT ON COLUMN "ruoyi"."sys_menu"."update_time" IS '更新时间';
COMMENT ON COLUMN "ruoyi"."sys_menu"."remark" IS '备注';

-- ----------------------------
-- Records of sys_menu
-- ----------------------------
INSERT INTO "ruoyi"."sys_menu" VALUES (1, '系统管理', 0, 10, 'system', NULL, '', '', 1, 0, 'M', '0', '0', '', 'system', 'admin', '2024-07-18 08:50:06', '', NULL, '系统管理目录');
INSERT INTO "ruoyi"."sys_menu" VALUES (2, '系统监控', 0, 11, 'monitor', NULL, '', '', 1, 0, 'M', '0', '0', '', 'monitor', 'admin', '2024-07-18 08:50:06', '', NULL, '系统监控目录');
INSERT INTO "ruoyi"."sys_menu" VALUES (3, '系统工具', 0, 12, 'tool', NULL, '', '', 1, 0, 'M', '0', '0', '', 'tool', 'admin', '2024-07-18 08:50:06', '', NULL, '系统工具目录');
INSERT INTO "ruoyi"."sys_menu" VALUES (100, '用户管理', 1, 1, 'user', 'system/user/index', '', '', 1, 0, 'C', '0', '0', 'system:user:list', 'user', 'admin', '2024-07-18 08:50:06', '', NULL, '用户管理菜单');
INSERT INTO "ruoyi"."sys_menu" VALUES (101, '角色管理', 1, 2, 'role', 'system/role/index', '', '', 1, 0, 'C', '0', '0', 'system:role:list', 'peoples', 'admin', '2024-07-18 08:50:06', '', NULL, '角色管理菜单');
INSERT INTO "ruoyi"."sys_menu" VALUES (102, '菜单管理', 1, 3, 'menu', 'system/menu/index', '', '', 1, 0, 'C', '0', '0', 'system:menu:list', 'tree-table', 'admin', '2024-07-18 08:50:06', '', NULL, '菜单管理菜单');
INSERT INTO "ruoyi"."sys_menu" VALUES (103, '部门管理', 1, 4, 'dept', 'system/dept/index', '', '', 1, 0, 'C', '0', '0', 'system:dept:list', 'tree', 'admin', '2024-07-18 08:50:06', '', NULL, '部门管理菜单');
INSERT INTO "ruoyi"."sys_menu" VALUES (104, '岗位管理', 1, 5, 'post', 'system/post/index', '', '', 1, 0, 'C', '0', '0', 'system:post:list', 'post', 'admin', '2024-07-18 08:50:06', '', NULL, '岗位管理菜单');
INSERT INTO "ruoyi"."sys_menu" VALUES (105, '字典管理', 1, 6, 'dict', 'system/dict/index', '', '', 1, 0, 'C', '0', '0', 'system:dict:list', 'dict', 'admin', '2024-07-18 08:50:06', '', NULL, '字典管理菜单');
INSERT INTO "ruoyi"."sys_menu" VALUES (106, '参数设置', 1, 7, 'config', 'system/config/index', '', '', 1, 0, 'C', '0', '0', 'system:config:list', 'edit', 'admin', '2024-07-18 08:50:06', '', NULL, '参数设置菜单');
INSERT INTO "ruoyi"."sys_menu" VALUES (107, '通知公告', 1, 8, 'notice', 'system/notice/index', '', '', 1, 0, 'C', '0', '0', 'system:notice:list', 'message', 'admin', '2024-07-18 08:50:06', '', NULL, '通知公告菜单');
INSERT INTO "ruoyi"."sys_menu" VALUES (108, '日志管理', 1, 9, 'log', '', '', '', 1, 0, 'M', '0', '0', '', 'log', 'admin', '2024-07-18 08:50:06', '', NULL, '日志管理菜单');
INSERT INTO "ruoyi"."sys_menu" VALUES (109, '在线用户', 2, 1, 'online', 'monitor/online/index', '', '', 1, 0, 'C', '0', '0', 'monitor:online:list', 'online', 'admin', '2024-07-18 08:50:06', '', NULL, '在线用户菜单');
INSERT INTO "ruoyi"."sys_menu" VALUES (110, '定时任务', 2, 2, 'job', 'monitor/job/index', '', '', 1, 0, 'C', '0', '0', 'monitor:job:list', 'job', 'admin', '2024-07-18 08:50:06', '', NULL, '定时任务菜单');
INSERT INTO "ruoyi"."sys_menu" VALUES (111, '数据监控', 2, 3, 'druid', 'monitor/druid/index', '', '', 1, 0, 'C', '0', '0', 'monitor:druid:list', 'druid', 'admin', '2024-07-18 08:50:06', '', NULL, '数据监控菜单');
INSERT INTO "ruoyi"."sys_menu" VALUES (112, '服务监控', 2, 4, 'server', 'monitor/server/index', '', '', 1, 0, 'C', '0', '0', 'monitor:server:list', 'server', 'admin', '2024-07-18 08:50:06', '', NULL, '服务监控菜单');
INSERT INTO "ruoyi"."sys_menu" VALUES (113, '缓存监控', 2, 5, 'cache', 'monitor/cache/index', '', '', 1, 0, 'C', '0', '0', 'monitor:cache:list', 'redis', 'admin', '2024-07-18 08:50:06', '', NULL, '缓存监控菜单');
INSERT INTO "ruoyi"."sys_menu" VALUES (114, '缓存列表', 2, 6, 'cacheList', 'monitor/cache/list', '', '', 1, 0, 'C', '0', '0', 'monitor:cache:list', 'redis-list', 'admin', '2024-07-18 08:50:06', '', NULL, '缓存列表菜单');
INSERT INTO "ruoyi"."sys_menu" VALUES (115, '表单构建', 3, 1, 'build', 'tool/build/index', '', '', 1, 0, 'C', '0', '0', 'tool:build:list', 'build', 'admin', '2025-03-18 14:13:07', '', NULL, '表单构建菜单');
INSERT INTO "ruoyi"."sys_menu" VALUES (116, '代码生成', 3, 2, 'gen', 'tool/gen/index', '', '', 1, 0, 'C', '0', '0', 'tool:gen:list', 'code', 'admin', '2024-07-18 08:50:06', '', NULL, '代码生成菜单');
INSERT INTO "ruoyi"."sys_menu" VALUES (500, '操作日志', 108, 1, 'operlog', 'monitor/operlog/index', '', '', 1, 0, 'C', '0', '0', 'monitor:operlog:list', 'form', 'admin', '2024-07-18 08:50:06', '', NULL, '操作日志菜单');
INSERT INTO "ruoyi"."sys_menu" VALUES (501, '登录日志', 108, 2, 'logininfor', 'monitor/logininfor/index', '', '', 1, 0, 'C', '0', '0', 'monitor:logininfor:list', 'logininfor', 'admin', '2024-07-18 08:50:06', '', NULL, '登录日志菜单');
INSERT INTO "ruoyi"."sys_menu" VALUES (1000, '用户查询', 100, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'system:user:query', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1001, '用户新增', 100, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'system:user:add', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1002, '用户修改', 100, 3, '', '', '', '', 1, 0, 'F', '0', '0', 'system:user:edit', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1003, '用户删除', 100, 4, '', '', '', '', 1, 0, 'F', '0', '0', 'system:user:remove', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1004, '用户导出', 100, 5, '', '', '', '', 1, 0, 'F', '0', '0', 'system:user:export', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1005, '用户导入', 100, 6, '', '', '', '', 1, 0, 'F', '0', '0', 'system:user:import', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1006, '重置密码', 100, 7, '', '', '', '', 1, 0, 'F', '0', '0', 'system:user:resetPwd', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1007, '角色查询', 101, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'system:role:query', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1008, '角色新增', 101, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'system:role:add', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1009, '角色修改', 101, 3, '', '', '', '', 1, 0, 'F', '0', '0', 'system:role:edit', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1010, '角色删除', 101, 4, '', '', '', '', 1, 0, 'F', '0', '0', 'system:role:remove', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1011, '角色导出', 101, 5, '', '', '', '', 1, 0, 'F', '0', '0', 'system:role:export', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1012, '菜单查询', 102, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'system:menu:query', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1013, '菜单新增', 102, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'system:menu:add', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1014, '菜单修改', 102, 3, '', '', '', '', 1, 0, 'F', '0', '0', 'system:menu:edit', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1015, '菜单删除', 102, 4, '', '', '', '', 1, 0, 'F', '0', '0', 'system:menu:remove', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1016, '部门查询', 103, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'system:dept:query', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1017, '部门新增', 103, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'system:dept:add', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1018, '部门修改', 103, 3, '', '', '', '', 1, 0, 'F', '0', '0', 'system:dept:edit', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1019, '部门删除', 103, 4, '', '', '', '', 1, 0, 'F', '0', '0', 'system:dept:remove', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1020, '岗位查询', 104, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'system:post:query', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1021, '岗位新增', 104, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'system:post:add', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1022, '岗位修改', 104, 3, '', '', '', '', 1, 0, 'F', '0', '0', 'system:post:edit', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1023, '岗位删除', 104, 4, '', '', '', '', 1, 0, 'F', '0', '0', 'system:post:remove', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1024, '岗位导出', 104, 5, '', '', '', '', 1, 0, 'F', '0', '0', 'system:post:export', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1025, '字典查询', 105, 1, '#', '', '', '', 1, 0, 'F', '0', '0', 'system:dict:query', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1026, '字典新增', 105, 2, '#', '', '', '', 1, 0, 'F', '0', '0', 'system:dict:add', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1027, '字典修改', 105, 3, '#', '', '', '', 1, 0, 'F', '0', '0', 'system:dict:edit', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1028, '字典删除', 105, 4, '#', '', '', '', 1, 0, 'F', '0', '0', 'system:dict:remove', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1029, '字典导出', 105, 5, '#', '', '', '', 1, 0, 'F', '0', '0', 'system:dict:export', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1030, '参数查询', 106, 1, '#', '', '', '', 1, 0, 'F', '0', '0', 'system:config:query', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1031, '参数新增', 106, 2, '#', '', '', '', 1, 0, 'F', '0', '0', 'system:config:add', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1032, '参数修改', 106, 3, '#', '', '', '', 1, 0, 'F', '0', '0', 'system:config:edit', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1033, '参数删除', 106, 4, '#', '', '', '', 1, 0, 'F', '0', '0', 'system:config:remove', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1034, '参数导出', 106, 5, '#', '', '', '', 1, 0, 'F', '0', '0', 'system:config:export', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1035, '公告查询', 107, 1, '#', '', '', '', 1, 0, 'F', '0', '0', 'system:notice:query', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1036, '公告新增', 107, 2, '#', '', '', '', 1, 0, 'F', '0', '0', 'system:notice:add', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1037, '公告修改', 107, 3, '#', '', '', '', 1, 0, 'F', '0', '0', 'system:notice:edit', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1038, '公告删除', 107, 4, '#', '', '', '', 1, 0, 'F', '0', '0', 'system:notice:remove', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1039, '操作查询', 500, 1, '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:operlog:query', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1040, '操作删除', 500, 2, '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:operlog:remove', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1041, '日志导出', 500, 3, '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:operlog:export', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1042, '登录查询', 501, 1, '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:logininfor:query', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1043, '登录删除', 501, 2, '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:logininfor:remove', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1044, '日志导出', 501, 3, '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:logininfor:export', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1045, '账户解锁', 501, 4, '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:logininfor:unlock', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1046, '在线查询', 109, 1, '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:online:query', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1047, '批量强退', 109, 2, '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:online:batchLogout', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1048, '单条强退', 109, 3, '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:online:forceLogout', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1049, '任务查询', 110, 1, '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:job:query', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1050, '任务新增', 110, 2, '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:job:add', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1051, '任务修改', 110, 3, '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:job:edit', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1052, '任务删除', 110, 4, '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:job:remove', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1053, '状态修改', 110, 5, '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:job:changeStatus', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1054, '任务导出', 110, 6, '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:job:export', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1055, '生成查询', 116, 1, '#', '', '', '', 1, 0, 'F', '0', '0', 'tool:gen:query', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1056, '生成修改', 116, 2, '#', '', '', '', 1, 0, 'F', '0', '0', 'tool:gen:edit', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1057, '生成删除', 116, 3, '#', '', '', '', 1, 0, 'F', '0', '0', 'tool:gen:remove', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1058, '导入代码', 116, 4, '#', '', '', '', 1, 0, 'F', '0', '0', 'tool:gen:import', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1059, '预览代码', 116, 5, '#', '', '', '', 1, 0, 'F', '0', '0', 'tool:gen:preview', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');
INSERT INTO "ruoyi"."sys_menu" VALUES (1060, '生成代码', 116, 6, '#', '', '', '', 1, 0, 'F', '0', '0', 'tool:gen:code', '#', 'admin', '2024-07-18 08:50:06', '', NULL, '');

-- ----------------------------
-- Table structure for sys_notice
-- ----------------------------
DROP TABLE IF EXISTS "ruoyi"."sys_notice";
CREATE TABLE "ruoyi"."sys_notice" (
  "notice_id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "notice_title" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "notice_type" char(1) COLLATE "pg_catalog"."default" NOT NULL,
  "notice_content" text COLLATE "pg_catalog"."default",
  "status" char(1) COLLATE "pg_catalog"."default" DEFAULT '0'::bpchar,
  "create_by" varchar(64) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "create_time" timestamp(6),
  "update_by" varchar(64) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "update_time" timestamp(6),
  "remark" varchar(255) COLLATE "pg_catalog"."default"
)
;
COMMENT ON COLUMN "ruoyi"."sys_notice"."notice_id" IS '公告ID';
COMMENT ON COLUMN "ruoyi"."sys_notice"."notice_title" IS '公告标题';
COMMENT ON COLUMN "ruoyi"."sys_notice"."notice_type" IS '公告类型（1通知 2公告）';
COMMENT ON COLUMN "ruoyi"."sys_notice"."notice_content" IS '公告内容';
COMMENT ON COLUMN "ruoyi"."sys_notice"."status" IS '公告状态（0正常 1关闭）';
COMMENT ON COLUMN "ruoyi"."sys_notice"."create_by" IS '创建者';
COMMENT ON COLUMN "ruoyi"."sys_notice"."create_time" IS '创建时间';
COMMENT ON COLUMN "ruoyi"."sys_notice"."update_by" IS '更新者';
COMMENT ON COLUMN "ruoyi"."sys_notice"."update_time" IS '更新时间';
COMMENT ON COLUMN "ruoyi"."sys_notice"."remark" IS '备注';

-- ----------------------------
-- Records of sys_notice
-- ----------------------------
INSERT INTO "ruoyi"."sys_notice" VALUES (3, 'fasf', '1', E'<p>fasff</p>', '0', 'admin', '2025-03-26 13:11:39.026033', '', NULL, NULL);
INSERT INTO "ruoyi"."sys_notice" VALUES (1, 'fasf', '1', E'<p>\\350\\256\\251\\346\\210\\221\\346\\226\\271\\346\\263\\225</p>', '0', 'admin', '2025-03-26 13:11:35.106139', 'admin', '2025-03-26 13:19:44.217518', NULL);
INSERT INTO "ruoyi"."sys_notice" VALUES (4, '发顺丰', '1', NULL, '0', 'admin', '2025-03-26 13:19:50.702297', '', NULL, NULL);
INSERT INTO "ruoyi"."sys_notice" VALUES (6, '分', '1', E'<p>\\\\fasfsfwf</p>', '0', 'admin', '2025-03-26 13:23:22.222397', 'admin', '2025-03-26 13:42:38.600707', NULL);
INSERT INTO "ruoyi"."sys_notice" VALUES (7, 'fwef', '1', E'<p>sfsfsfsfsfwef11</p>', '0', 'admin', '2025-03-26 14:11:32.561246', 'admin', '2025-03-26 14:11:44.194285', NULL);
INSERT INTO "ruoyi"."sys_notice" VALUES (5, '发顺丰', '2', E'<p>\\345\\217\\221\\347\\203\\247\\345\\274\\200\\350\\277\\233\\346\\235\\2453\\345\\217\\25323\\350\\247\\243\\345\\260\\201\\344\\272\\206\\345\\217\\221\\345\\217\\221</p><table><tbody><tr class="firstRow"><td width="195" valign="top"><br/></td><td width="195" valign="top"><br/></td><td width="195" valign="top" style="word-break: break-all;">2</td></tr><tr><td width="195" valign="top"><br/></td><td width="195" valign="top" style="word-break: break-all;">1</td><td width="195" valign="top"><br/></td></tr><tr><td width="195" valign="top"><br/></td><td width="195" valign="top"><br/></td><td width="195" valign="top"><br/></td></tr><tr><td width="195" valign="top"><br/></td><td width="195" valign="top"><br/></td><td width="195" valign="top"><br/></td></tr><tr><td width="195" valign="top" style="word-break: break-all;">3</td><td width="195" valign="top"><br/></td><td width="195" valign="top"><br/></td></tr><tr><td width="195" valign="top" style="word-break: break-all;">\\345\\217\\221\\351\\241\\272\\344\\270\\260</td><td width="195" valign="top"><br/></td><td width="195" valign="top"><br/></td></tr><tr><td width="195" valign="top"><br/></td><td width="195" valign="top"><br/></td><td width="195" valign="top"><br/></td></tr></tbody></table><p><br/></p>', '0', 'admin', '2025-03-26 13:21:38.257319', 'admin', '2025-03-26 14:11:51.484802', NULL);
INSERT INTO "ruoyi"."sys_notice" VALUES (2, 'fasf', '1', E'<p>fasff</p>', '0', 'admin', '2025-03-26 13:11:38.033979', 'admin', '2025-03-26 14:13:13.441895', NULL);

-- ----------------------------
-- Table structure for sys_oper_log
-- ----------------------------
DROP TABLE IF EXISTS "ruoyi"."sys_oper_log";
CREATE TABLE "ruoyi"."sys_oper_log" (
  "oper_id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "title" varchar(50) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "business_type" int4 DEFAULT 0,
  "method" varchar(200) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "request_method" varchar(10) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "operator_type" int4 DEFAULT 0,
  "oper_name" varchar(50) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "dept_name" varchar(50) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "oper_url" varchar(255) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "oper_ip" varchar(128) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "oper_location" varchar(255) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "oper_param" varchar(5000) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "json_result" varchar(5000) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "status" int4 DEFAULT 0,
  "error_msg" varchar(5000) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "oper_time" timestamp(6),
  "cost_time" int8 DEFAULT '0'::bigint
)
;
COMMENT ON COLUMN "ruoyi"."sys_oper_log"."oper_id" IS '日志主键';
COMMENT ON COLUMN "ruoyi"."sys_oper_log"."title" IS '模块标题';
COMMENT ON COLUMN "ruoyi"."sys_oper_log"."business_type" IS '业务类型（0其它 1新增 2修改 3删除）';
COMMENT ON COLUMN "ruoyi"."sys_oper_log"."method" IS '方法名称';
COMMENT ON COLUMN "ruoyi"."sys_oper_log"."request_method" IS '请求方式';
COMMENT ON COLUMN "ruoyi"."sys_oper_log"."operator_type" IS '操作类别（0其它 1后台用户 2手机端用户）';
COMMENT ON COLUMN "ruoyi"."sys_oper_log"."oper_name" IS '操作人员';
COMMENT ON COLUMN "ruoyi"."sys_oper_log"."dept_name" IS '部门名称';
COMMENT ON COLUMN "ruoyi"."sys_oper_log"."oper_url" IS '请求URL';
COMMENT ON COLUMN "ruoyi"."sys_oper_log"."oper_ip" IS '主机地址';
COMMENT ON COLUMN "ruoyi"."sys_oper_log"."oper_location" IS '操作地点';
COMMENT ON COLUMN "ruoyi"."sys_oper_log"."oper_param" IS '请求参数';
COMMENT ON COLUMN "ruoyi"."sys_oper_log"."json_result" IS '返回参数';
COMMENT ON COLUMN "ruoyi"."sys_oper_log"."status" IS '操作状态（0正常 1异常）';
COMMENT ON COLUMN "ruoyi"."sys_oper_log"."error_msg" IS '错误消息';
COMMENT ON COLUMN "ruoyi"."sys_oper_log"."oper_time" IS '操作时间';
COMMENT ON COLUMN "ruoyi"."sys_oper_log"."cost_time" IS '消耗时间';

-- ----------------------------
-- Records of sys_oper_log
-- ----------------------------

-- ----------------------------
-- Table structure for sys_post
-- ----------------------------
DROP TABLE IF EXISTS "ruoyi"."sys_post";
CREATE TABLE "ruoyi"."sys_post" (
  "post_id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "post_code" varchar(64) COLLATE "pg_catalog"."default" NOT NULL,
  "post_name" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "post_sort" int4 NOT NULL,
  "status" char(1) COLLATE "pg_catalog"."default" NOT NULL,
  "create_by" varchar(64) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "create_time" timestamp(6),
  "update_by" varchar(64) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "update_time" timestamp(6),
  "remark" varchar(500) COLLATE "pg_catalog"."default"
)
;
COMMENT ON COLUMN "ruoyi"."sys_post"."post_id" IS '岗位ID';
COMMENT ON COLUMN "ruoyi"."sys_post"."post_code" IS '岗位编码';
COMMENT ON COLUMN "ruoyi"."sys_post"."post_name" IS '岗位名称';
COMMENT ON COLUMN "ruoyi"."sys_post"."post_sort" IS '显示顺序';
COMMENT ON COLUMN "ruoyi"."sys_post"."status" IS '状态（0正常 1停用）';
COMMENT ON COLUMN "ruoyi"."sys_post"."create_by" IS '创建者';
COMMENT ON COLUMN "ruoyi"."sys_post"."create_time" IS '创建时间';
COMMENT ON COLUMN "ruoyi"."sys_post"."update_by" IS '更新者';
COMMENT ON COLUMN "ruoyi"."sys_post"."update_time" IS '更新时间';
COMMENT ON COLUMN "ruoyi"."sys_post"."remark" IS '备注';

-- ----------------------------
-- Records of sys_post
-- ----------------------------
INSERT INTO "ruoyi"."sys_post" VALUES (1, 'admin', '系统管理员', 1, '0', 'admin', '2024-07-18 08:50:06', 'admin', '2025-03-26 11:56:53.452394', '');

-- ----------------------------
-- Table structure for sys_role
-- ----------------------------
DROP TABLE IF EXISTS "ruoyi"."sys_role";
CREATE TABLE "ruoyi"."sys_role" (
  "role_id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "role_name" varchar(30) COLLATE "pg_catalog"."default" NOT NULL,
  "role_key" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "role_sort" int4 NOT NULL,
  "data_scope" char(1) COLLATE "pg_catalog"."default" DEFAULT '1'::bpchar,
  "menu_check_strictly" int2 DEFAULT '1'::smallint,
  "dept_check_strictly" int2 DEFAULT '1'::smallint,
  "status" char(1) COLLATE "pg_catalog"."default" NOT NULL,
  "del_flag" char(1) COLLATE "pg_catalog"."default" DEFAULT '0'::bpchar,
  "create_by" varchar(64) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "create_time" timestamp(6),
  "update_by" varchar(64) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "update_time" timestamp(6),
  "remark" varchar(500) COLLATE "pg_catalog"."default"
)
;
COMMENT ON COLUMN "ruoyi"."sys_role"."role_id" IS '角色ID';
COMMENT ON COLUMN "ruoyi"."sys_role"."role_name" IS '角色名称';
COMMENT ON COLUMN "ruoyi"."sys_role"."role_key" IS '角色权限字符串';
COMMENT ON COLUMN "ruoyi"."sys_role"."role_sort" IS '显示顺序';
COMMENT ON COLUMN "ruoyi"."sys_role"."data_scope" IS '数据范围（1：全部数据权限 2：自定数据权限 3：本部门数据权限 4：本部门及以下数据权限）';
COMMENT ON COLUMN "ruoyi"."sys_role"."menu_check_strictly" IS '菜单树选择项是否关联显示';
COMMENT ON COLUMN "ruoyi"."sys_role"."dept_check_strictly" IS '部门树选择项是否关联显示';
COMMENT ON COLUMN "ruoyi"."sys_role"."status" IS '角色状态（0正常 1停用）';
COMMENT ON COLUMN "ruoyi"."sys_role"."del_flag" IS '删除标志（0代表存在 2代表删除）';
COMMENT ON COLUMN "ruoyi"."sys_role"."create_by" IS '创建者';
COMMENT ON COLUMN "ruoyi"."sys_role"."create_time" IS '创建时间';
COMMENT ON COLUMN "ruoyi"."sys_role"."update_by" IS '更新者';
COMMENT ON COLUMN "ruoyi"."sys_role"."update_time" IS '更新时间';
COMMENT ON COLUMN "ruoyi"."sys_role"."remark" IS '备注';

-- ----------------------------
-- Records of sys_role
-- ----------------------------
INSERT INTO "ruoyi"."sys_role" VALUES (1, '超级管理员', 'admin', 1, '1', 1, 1, '0', '0', 'admin', '2024-07-18 08:50:06', '', NULL, '超级管理员');
INSERT INTO "ruoyi"."sys_role" VALUES (2, '普通角色', 'common', 2, '2', 1, 1, '0', '2', 'admin', '2024-07-18 08:50:06', '', NULL, '普通角色');

-- ----------------------------
-- Table structure for sys_role_dept
-- ----------------------------
DROP TABLE IF EXISTS "ruoyi"."sys_role_dept";
CREATE TABLE "ruoyi"."sys_role_dept" (
  "role_id" int8 NOT NULL,
  "dept_id" int8 NOT NULL
)
;
COMMENT ON COLUMN "ruoyi"."sys_role_dept"."role_id" IS '角色ID';
COMMENT ON COLUMN "ruoyi"."sys_role_dept"."dept_id" IS '部门ID';

-- ----------------------------
-- Records of sys_role_dept
-- ----------------------------

-- ----------------------------
-- Table structure for sys_role_menu
-- ----------------------------
DROP TABLE IF EXISTS "ruoyi"."sys_role_menu";
CREATE TABLE "ruoyi"."sys_role_menu" (
  "role_id" int8 NOT NULL,
  "menu_id" int8 NOT NULL
)
;
COMMENT ON COLUMN "ruoyi"."sys_role_menu"."role_id" IS '角色ID';
COMMENT ON COLUMN "ruoyi"."sys_role_menu"."menu_id" IS '菜单ID';

-- ----------------------------
-- Records of sys_role_menu
-- ----------------------------

-- ----------------------------
-- Table structure for sys_user
-- ----------------------------
DROP TABLE IF EXISTS "ruoyi"."sys_user";
CREATE TABLE "ruoyi"."sys_user" (
  "user_id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "dept_id" int8,
  "user_name" varchar(30) COLLATE "pg_catalog"."default" NOT NULL,
  "nick_name" varchar(30) COLLATE "pg_catalog"."default" NOT NULL,
  "user_type" varchar(2) COLLATE "pg_catalog"."default" DEFAULT '00'::character varying,
  "email" varchar(50) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "phonenumber" varchar(11) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "sex" char(1) COLLATE "pg_catalog"."default" DEFAULT '0'::bpchar,
  "avatar" varchar(100) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "password" varchar(100) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "status" char(1) COLLATE "pg_catalog"."default" DEFAULT '0'::bpchar,
  "del_flag" char(1) COLLATE "pg_catalog"."default" DEFAULT '0'::bpchar,
  "login_ip" varchar(128) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "login_date" timestamp(6),
  "pwd_update_date" timestamp(6),
  "try_count" int8,
  "create_by" varchar(64) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "create_time" timestamp(6),
  "update_by" varchar(64) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "update_time" timestamp(6),
  "remark" varchar(500) COLLATE "pg_catalog"."default"
)
;
COMMENT ON COLUMN "ruoyi"."sys_user"."user_id" IS '用户ID';
COMMENT ON COLUMN "ruoyi"."sys_user"."dept_id" IS '部门ID';
COMMENT ON COLUMN "ruoyi"."sys_user"."user_name" IS '用户账号';
COMMENT ON COLUMN "ruoyi"."sys_user"."nick_name" IS '用户昵称';
COMMENT ON COLUMN "ruoyi"."sys_user"."user_type" IS '用户类型（00系统用户）';
COMMENT ON COLUMN "ruoyi"."sys_user"."email" IS '用户邮箱';
COMMENT ON COLUMN "ruoyi"."sys_user"."phonenumber" IS '手机号码';
COMMENT ON COLUMN "ruoyi"."sys_user"."sex" IS '用户性别（0男 1女 2未知）';
COMMENT ON COLUMN "ruoyi"."sys_user"."avatar" IS '头像地址';
COMMENT ON COLUMN "ruoyi"."sys_user"."password" IS '密码';
COMMENT ON COLUMN "ruoyi"."sys_user"."status" IS '账号状态（0正常 1停用）';
COMMENT ON COLUMN "ruoyi"."sys_user"."del_flag" IS '删除标志（0代表存在 2代表删除）';
COMMENT ON COLUMN "ruoyi"."sys_user"."login_ip" IS '最后登录IP';
COMMENT ON COLUMN "ruoyi"."sys_user"."login_date" IS '最后登录时间';
COMMENT ON COLUMN "ruoyi"."sys_user"."pwd_update_date" IS '密码最后更新时间';
COMMENT ON COLUMN "ruoyi"."sys_user"."try_count" IS '尝试登录次数';
COMMENT ON COLUMN "ruoyi"."sys_user"."create_by" IS '创建者';
COMMENT ON COLUMN "ruoyi"."sys_user"."create_time" IS '创建时间';
COMMENT ON COLUMN "ruoyi"."sys_user"."update_by" IS '更新者';
COMMENT ON COLUMN "ruoyi"."sys_user"."update_time" IS '更新时间';
COMMENT ON COLUMN "ruoyi"."sys_user"."remark" IS '备注';

-- ----------------------------
-- Records of sys_user
-- ----------------------------
INSERT INTO "ruoyi"."sys_user" VALUES (1, 100, 'admin', 'admin', '00', 'jiangyanxi@live.com', '15553502062', '0', '', '$2a$10$56cMm3yK5AQ2vVqatR.FBuaEePzh13vg0f1ckfjCJKQN0QDwYRyF.', '0', '0', '127.0.0.1', '2025-03-26 14:56:20.37', '2025-03-26 14:56:20.37',0, 'admin', '2024-07-18 08:50:06', '', '2025-03-26 14:56:07.07615', '管理员');

-- ----------------------------
-- Table structure for sys_user_post
-- ----------------------------
DROP TABLE IF EXISTS "ruoyi"."sys_user_post";
CREATE TABLE "ruoyi"."sys_user_post" (
  "user_id" int8 NOT NULL,
  "post_id" int8 NOT NULL
)
;
COMMENT ON COLUMN "ruoyi"."sys_user_post"."user_id" IS '用户ID';
COMMENT ON COLUMN "ruoyi"."sys_user_post"."post_id" IS '岗位ID';

-- ----------------------------
-- Records of sys_user_post
-- ----------------------------
INSERT INTO "ruoyi"."sys_user_post" VALUES (1, 1);

-- ----------------------------
-- Table structure for sys_user_role
-- ----------------------------
DROP TABLE IF EXISTS "ruoyi"."sys_user_role";
CREATE TABLE "ruoyi"."sys_user_role" (
  "user_id" int8 NOT NULL,
  "role_id" int8 NOT NULL
)
;
COMMENT ON COLUMN "ruoyi"."sys_user_role"."user_id" IS '用户ID';
COMMENT ON COLUMN "ruoyi"."sys_user_role"."role_id" IS '角色ID';

-- ----------------------------
-- Records of sys_user_role
-- ----------------------------
INSERT INTO "ruoyi"."sys_user_role" VALUES (1, 1);

-- ----------------------------
-- Function structure for substring_index
-- ----------------------------
DROP FUNCTION IF EXISTS "ruoyi"."substring_index"(varchar, varchar, int4);
CREATE FUNCTION "ruoyi"."substring_index"(varchar, varchar, int4)
  RETURNS "pg_catalog"."varchar" AS $BODY$
DECLARE
tokens varchar[];
length integer ;
indexnum integer;
BEGIN
tokens := pg_catalog.string_to_array($1, $2);
length := pg_catalog.array_upper(tokens, 1);
indexnum := length - ($3 * -1) + 1;
IF $3 >= 0 THEN
RETURN pg_catalog.array_to_string(tokens[1:$3], $2);
ELSE
RETURN pg_catalog.array_to_string(tokens[indexnum:length], $2);
END IF;
END;
$BODY$
  LANGUAGE plpgsql IMMUTABLE STRICT
  COST 100;

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "ruoyi"."gen_table_column_column_id_seq"
OWNED BY "ruoyi"."gen_table_column"."column_id";
SELECT setval('"ruoyi"."gen_table_column_column_id_seq"', 48, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "ruoyi"."gen_table_table_id_seq"
OWNED BY "ruoyi"."gen_table"."table_id";
SELECT setval('"ruoyi"."gen_table_table_id_seq"', 29, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "ruoyi"."sys_config_config_id_seq"
OWNED BY "ruoyi"."sys_config"."config_id";
SELECT setval('"ruoyi"."sys_config_config_id_seq"', 7, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "ruoyi"."sys_dept_dept_id_seq"
OWNED BY "ruoyi"."sys_dept"."dept_id";
SELECT setval('"ruoyi"."sys_dept_dept_id_seq"', 1, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "ruoyi"."sys_dict_data_dict_code_seq"
OWNED BY "ruoyi"."sys_dict_data"."dict_code";
SELECT setval('"ruoyi"."sys_dict_data_dict_code_seq"', 10000, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "ruoyi"."sys_dict_type_dict_id_seq"
OWNED BY "ruoyi"."sys_dict_type"."dict_id";
SELECT setval('"ruoyi"."sys_dict_type_dict_id_seq"', 3340, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "ruoyi"."sys_job_job_id_seq"
OWNED BY "ruoyi"."sys_job"."job_id";
SELECT setval('"ruoyi"."sys_job_job_id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "ruoyi"."sys_job_log_job_log_id_seq"
OWNED BY "ruoyi"."sys_job_log"."job_log_id";
SELECT setval('"ruoyi"."sys_job_log_job_log_id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "ruoyi"."sys_logininfor_info_id_seq"
OWNED BY "ruoyi"."sys_logininfor"."info_id";
SELECT setval('"ruoyi"."sys_logininfor_info_id_seq"', 1, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "ruoyi"."sys_menu_menu_id_seq"
OWNED BY "ruoyi"."sys_menu"."menu_id";
SELECT setval('"ruoyi"."sys_menu_menu_id_seq"', 6, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "ruoyi"."sys_notice_notice_id_seq"
OWNED BY "ruoyi"."sys_notice"."notice_id";
SELECT setval('"ruoyi"."sys_notice_notice_id_seq"', 7, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "ruoyi"."sys_oper_log_oper_id_seq"
OWNED BY "ruoyi"."sys_oper_log"."oper_id";
SELECT setval('"ruoyi"."sys_oper_log_oper_id_seq"', 84, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "ruoyi"."sys_post_post_id_seq"
OWNED BY "ruoyi"."sys_post"."post_id";
SELECT setval('"ruoyi"."sys_post_post_id_seq"', 3, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "ruoyi"."sys_role_role_id_seq"
OWNED BY "ruoyi"."sys_role"."role_id";
SELECT setval('"ruoyi"."sys_role_role_id_seq"', 4, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "ruoyi"."sys_user_user_id_seq"
OWNED BY "ruoyi"."sys_user"."user_id";
SELECT setval('"ruoyi"."sys_user_user_id_seq"', 5, true);

-- ----------------------------
-- Auto increment value for gen_table
-- ----------------------------
SELECT setval('"ruoyi"."gen_table_table_id_seq"', 29, true);

-- ----------------------------
-- Primary Key structure for table gen_table
-- ----------------------------
ALTER TABLE "ruoyi"."gen_table" ADD CONSTRAINT "gen_table_pkey" PRIMARY KEY ("table_id");

-- ----------------------------
-- Auto increment value for gen_table_column
-- ----------------------------
SELECT setval('"ruoyi"."gen_table_column_column_id_seq"', 48, true);

-- ----------------------------
-- Primary Key structure for table gen_table_column
-- ----------------------------
ALTER TABLE "ruoyi"."gen_table_column" ADD CONSTRAINT "gen_table_column_pkey" PRIMARY KEY ("column_id");

-- ----------------------------
-- Primary Key structure for table qrtz_blob_triggers
-- ----------------------------
ALTER TABLE "ruoyi"."qrtz_blob_triggers" ADD CONSTRAINT "qrtz_blob_triggers_pkey" PRIMARY KEY ("trigger_name", "sched_name", "trigger_group");

-- ----------------------------
-- Primary Key structure for table qrtz_calendars
-- ----------------------------
ALTER TABLE "ruoyi"."qrtz_calendars" ADD CONSTRAINT "qrtz_calendars_pkey" PRIMARY KEY ("calendar_name", "sched_name");

-- ----------------------------
-- Primary Key structure for table qrtz_cron_triggers
-- ----------------------------
ALTER TABLE "ruoyi"."qrtz_cron_triggers" ADD CONSTRAINT "qrtz_cron_triggers_pkey" PRIMARY KEY ("trigger_name", "sched_name", "trigger_group");

-- ----------------------------
-- Primary Key structure for table qrtz_fired_triggers
-- ----------------------------
ALTER TABLE "ruoyi"."qrtz_fired_triggers" ADD CONSTRAINT "qrtz_fired_triggers_pkey" PRIMARY KEY ("entry_id", "sched_name");

-- ----------------------------
-- Primary Key structure for table qrtz_job_details
-- ----------------------------
ALTER TABLE "ruoyi"."qrtz_job_details" ADD CONSTRAINT "qrtz_job_details_pkey" PRIMARY KEY ("job_name", "sched_name", "job_group");

-- ----------------------------
-- Primary Key structure for table qrtz_locks
-- ----------------------------
ALTER TABLE "ruoyi"."qrtz_locks" ADD CONSTRAINT "qrtz_locks_pkey" PRIMARY KEY ("lock_name", "sched_name");

-- ----------------------------
-- Primary Key structure for table qrtz_paused_trigger_grps
-- ----------------------------
ALTER TABLE "ruoyi"."qrtz_paused_trigger_grps" ADD CONSTRAINT "qrtz_paused_trigger_grps_pkey" PRIMARY KEY ("sched_name", "trigger_group");

-- ----------------------------
-- Primary Key structure for table qrtz_scheduler_state
-- ----------------------------
ALTER TABLE "ruoyi"."qrtz_scheduler_state" ADD CONSTRAINT "qrtz_scheduler_state_pkey" PRIMARY KEY ("instance_name", "sched_name");

-- ----------------------------
-- Primary Key structure for table qrtz_simple_triggers
-- ----------------------------
ALTER TABLE "ruoyi"."qrtz_simple_triggers" ADD CONSTRAINT "qrtz_simple_triggers_pkey" PRIMARY KEY ("trigger_group", "trigger_name", "sched_name");

-- ----------------------------
-- Primary Key structure for table qrtz_simprop_triggers
-- ----------------------------
ALTER TABLE "ruoyi"."qrtz_simprop_triggers" ADD CONSTRAINT "qrtz_simprop_triggers_pkey" PRIMARY KEY ("trigger_group", "trigger_name", "sched_name");

-- ----------------------------
-- Indexes structure for table qrtz_triggers
-- ----------------------------
CREATE INDEX "qrtz_triggerssched_name" ON "ruoyi"."qrtz_triggers" USING btree (
  "sched_name" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "job_name" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "job_group" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table qrtz_triggers
-- ----------------------------
ALTER TABLE "ruoyi"."qrtz_triggers" ADD CONSTRAINT "qrtz_triggers_pkey" PRIMARY KEY ("trigger_group", "trigger_name", "sched_name");

-- ----------------------------
-- Auto increment value for sys_config
-- ----------------------------
SELECT setval('"ruoyi"."sys_config_config_id_seq"', 7, true);

-- ----------------------------
-- Primary Key structure for table sys_config
-- ----------------------------
ALTER TABLE "ruoyi"."sys_config" ADD CONSTRAINT "sys_config_pkey" PRIMARY KEY ("config_id");

-- ----------------------------
-- Auto increment value for sys_dept
-- ----------------------------
SELECT setval('"ruoyi"."sys_dept_dept_id_seq"', 1, true);

-- ----------------------------
-- Primary Key structure for table sys_dept
-- ----------------------------
ALTER TABLE "ruoyi"."sys_dept" ADD CONSTRAINT "sys_dept_pkey" PRIMARY KEY ("dept_id");

-- ----------------------------
-- Auto increment value for sys_dict_data
-- ----------------------------
SELECT setval('"ruoyi"."sys_dict_data_dict_code_seq"', 10000, true);

-- ----------------------------
-- Primary Key structure for table sys_dict_data
-- ----------------------------
ALTER TABLE "ruoyi"."sys_dict_data" ADD CONSTRAINT "sys_dict_data_pkey" PRIMARY KEY ("dict_code");

-- ----------------------------
-- Auto increment value for sys_dict_type
-- ----------------------------
SELECT setval('"ruoyi"."sys_dict_type_dict_id_seq"', 3340, true);

-- ----------------------------
-- Uniques structure for table sys_dict_type
-- ----------------------------
ALTER TABLE "ruoyi"."sys_dict_type" ADD CONSTRAINT "sys_dict_type_dict_type" UNIQUE ("dict_type");

-- ----------------------------
-- Primary Key structure for table sys_dict_type
-- ----------------------------
ALTER TABLE "ruoyi"."sys_dict_type" ADD CONSTRAINT "sys_dict_type_pkey" PRIMARY KEY ("dict_id");

-- ----------------------------
-- Auto increment value for sys_job
-- ----------------------------
SELECT setval('"ruoyi"."sys_job_job_id_seq"', 1, false);

-- ----------------------------
-- Primary Key structure for table sys_job
-- ----------------------------
ALTER TABLE "ruoyi"."sys_job" ADD CONSTRAINT "sys_job_pkey" PRIMARY KEY ("job_group", "job_name", "job_id");

-- ----------------------------
-- Auto increment value for sys_job_log
-- ----------------------------
SELECT setval('"ruoyi"."sys_job_log_job_log_id_seq"', 1, false);

-- ----------------------------
-- Primary Key structure for table sys_job_log
-- ----------------------------
ALTER TABLE "ruoyi"."sys_job_log" ADD CONSTRAINT "sys_job_log_pkey" PRIMARY KEY ("job_log_id");

-- ----------------------------
-- Auto increment value for sys_logininfor
-- ----------------------------
SELECT setval('"ruoyi"."sys_logininfor_info_id_seq"', 1, true);

-- ----------------------------
-- Indexes structure for table sys_logininfor
-- ----------------------------
CREATE INDEX "sys_logininforidx_sys_logininfor_lt" ON "ruoyi"."sys_logininfor" USING btree (
  "login_time" "pg_catalog"."timestamp_ops" ASC NULLS LAST
);
CREATE INDEX "sys_logininforidx_sys_logininfor_s" ON "ruoyi"."sys_logininfor" USING btree (
  "status" COLLATE "pg_catalog"."default" "pg_catalog"."bpchar_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table sys_logininfor
-- ----------------------------
ALTER TABLE "ruoyi"."sys_logininfor" ADD CONSTRAINT "sys_logininfor_pkey" PRIMARY KEY ("info_id");

-- ----------------------------
-- Auto increment value for sys_menu
-- ----------------------------
SELECT setval('"ruoyi"."sys_menu_menu_id_seq"', 6, true);

-- ----------------------------
-- Primary Key structure for table sys_menu
-- ----------------------------
ALTER TABLE "ruoyi"."sys_menu" ADD CONSTRAINT "sys_menu_pkey" PRIMARY KEY ("menu_id");

-- ----------------------------
-- Auto increment value for sys_notice
-- ----------------------------
SELECT setval('"ruoyi"."sys_notice_notice_id_seq"', 7, true);

-- ----------------------------
-- Primary Key structure for table sys_notice
-- ----------------------------
ALTER TABLE "ruoyi"."sys_notice" ADD CONSTRAINT "sys_notice_pkey" PRIMARY KEY ("notice_id");

-- ----------------------------
-- Auto increment value for sys_oper_log
-- ----------------------------
SELECT setval('"ruoyi"."sys_oper_log_oper_id_seq"', 84, true);

-- ----------------------------
-- Indexes structure for table sys_oper_log
-- ----------------------------
CREATE INDEX "sys_oper_logidx_sys_oper_log_bt" ON "ruoyi"."sys_oper_log" USING btree (
  "business_type" "pg_catalog"."int4_ops" ASC NULLS LAST
);
CREATE INDEX "sys_oper_logidx_sys_oper_log_ot" ON "ruoyi"."sys_oper_log" USING btree (
  "oper_time" "pg_catalog"."timestamp_ops" ASC NULLS LAST
);
CREATE INDEX "sys_oper_logidx_sys_oper_log_s" ON "ruoyi"."sys_oper_log" USING btree (
  "status" "pg_catalog"."int4_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table sys_oper_log
-- ----------------------------
ALTER TABLE "ruoyi"."sys_oper_log" ADD CONSTRAINT "sys_oper_log_pkey" PRIMARY KEY ("oper_id");

-- ----------------------------
-- Auto increment value for sys_post
-- ----------------------------
SELECT setval('"ruoyi"."sys_post_post_id_seq"', 3, true);

-- ----------------------------
-- Primary Key structure for table sys_post
-- ----------------------------
ALTER TABLE "ruoyi"."sys_post" ADD CONSTRAINT "sys_post_pkey" PRIMARY KEY ("post_id");

-- ----------------------------
-- Auto increment value for sys_role
-- ----------------------------
SELECT setval('"ruoyi"."sys_role_role_id_seq"', 4, true);

-- ----------------------------
-- Primary Key structure for table sys_role
-- ----------------------------
ALTER TABLE "ruoyi"."sys_role" ADD CONSTRAINT "sys_role_pkey" PRIMARY KEY ("role_id");

-- ----------------------------
-- Primary Key structure for table sys_role_dept
-- ----------------------------
ALTER TABLE "ruoyi"."sys_role_dept" ADD CONSTRAINT "sys_role_dept_pkey" PRIMARY KEY ("role_id", "dept_id");

-- ----------------------------
-- Primary Key structure for table sys_role_menu
-- ----------------------------
ALTER TABLE "ruoyi"."sys_role_menu" ADD CONSTRAINT "sys_role_menu_pkey" PRIMARY KEY ("role_id", "menu_id");

-- ----------------------------
-- Auto increment value for sys_user
-- ----------------------------
SELECT setval('"ruoyi"."sys_user_user_id_seq"', 5, true);

-- ----------------------------
-- Primary Key structure for table sys_user
-- ----------------------------
ALTER TABLE "ruoyi"."sys_user" ADD CONSTRAINT "sys_user_pkey" PRIMARY KEY ("user_id");

-- ----------------------------
-- Primary Key structure for table sys_user_post
-- ----------------------------
ALTER TABLE "ruoyi"."sys_user_post" ADD CONSTRAINT "sys_user_post_pkey" PRIMARY KEY ("post_id", "user_id");

-- ----------------------------
-- Primary Key structure for table sys_user_role
-- ----------------------------
ALTER TABLE "ruoyi"."sys_user_role" ADD CONSTRAINT "sys_user_role_pkey" PRIMARY KEY ("role_id", "user_id");

-- ----------------------------
-- Foreign Keys structure for table qrtz_blob_triggers
-- ----------------------------
ALTER TABLE "ruoyi"."qrtz_blob_triggers" ADD CONSTRAINT "qrtz_blob_triggers_ibfk_1" FOREIGN KEY ("sched_name", "trigger_group", "trigger_name") REFERENCES "ruoyi"."qrtz_triggers" ("sched_name", "trigger_group", "trigger_name") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- ----------------------------
-- Foreign Keys structure for table qrtz_cron_triggers
-- ----------------------------
ALTER TABLE "ruoyi"."qrtz_cron_triggers" ADD CONSTRAINT "qrtz_cron_triggers_ibfk_1" FOREIGN KEY ("trigger_group", "trigger_name", "sched_name") REFERENCES "ruoyi"."qrtz_triggers" ("sched_name", "trigger_group", "trigger_name") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- ----------------------------
-- Foreign Keys structure for table qrtz_simple_triggers
-- ----------------------------
ALTER TABLE "ruoyi"."qrtz_simple_triggers" ADD CONSTRAINT "qrtz_simple_triggers_ibfk_1" FOREIGN KEY ("trigger_name", "sched_name", "trigger_group") REFERENCES "ruoyi"."qrtz_triggers" ("sched_name", "trigger_group", "trigger_name") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- ----------------------------
-- Foreign Keys structure for table qrtz_simprop_triggers
-- ----------------------------
ALTER TABLE "ruoyi"."qrtz_simprop_triggers" ADD CONSTRAINT "qrtz_simprop_triggers_ibfk_1" FOREIGN KEY ("sched_name", "trigger_group", "trigger_name") REFERENCES "ruoyi"."qrtz_triggers" ("trigger_name", "sched_name", "trigger_group") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- ----------------------------
-- Foreign Keys structure for table qrtz_triggers
-- ----------------------------
ALTER TABLE "ruoyi"."qrtz_triggers" ADD CONSTRAINT "qrtz_triggers_ibfk_1" FOREIGN KEY ("sched_name", "job_group", "job_name") REFERENCES "ruoyi"."qrtz_job_details" ("sched_name", "job_group", "job_name") ON DELETE RESTRICT ON UPDATE RESTRICT;
